/*
 * Copyright (c) 2012 Adobe Systems Incorporated. All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

/*jslint vars: true, plusplus: true, devel: true, nomen: true, indent: 4, maxerr: 50 */
/*global define */

define({

    "GENERIC_ERROR": "(chyba {0})",
    "NOT_FOUND_ERR": "Soubor /directory nelze nalézt.",
    "NOT_READABLE_ERR": "Soubor /directory nelze přečíst.",
    "EXCEEDS_MAX_FILE_SIZE": "Soubor větší než {0} MB nemůže být otevřen v {APP_NAME}.",
    "NO_MODIFICATION_ALLOWED_ERR": "Cílová složka nemůže být změněna.",
    "NO_MODIFICATION_ALLOWED_ERR_FILE": "Oprávnění neumožní provádět změny.",
    "CONTENTS_MODIFIED_ERR": "Soubor byl změněn mimo aplikaci {APP_NAME}.",
    "UNSUPPORTED_ENCODING_ERR": "{APP_NAME} v této chvíli podporuje pouze UTF-8 textové soubory.",
    "FILE_EXISTS_ERR": "Soubor nebo složka již existuje.",
    "FILE": "soubor",
    "FILE_TITLE": "Soubor",
    "DIRECTORY": "složka",
    "DIRECTORY_TITLE": "Složka",
    "DIRECTORY_NAMES_LEDE": "Názvy složek",
    "FILENAMES_LEDE": "Názvy souborů",
    "FILENAME": "Název souboru",
    "DIRECTORY_NAME": "Název složky",
    "ERROR_LOADING_PROJECT": "Chyba při otevírání projektu",
    "OPEN_DIALOG_ERROR": "Při zobrazování dialogu pro otevření souboru došlo k chybě. (chyba {0})",
    "REQUEST_NATIVE_FILE_SYSTEM_ERROR": "Došlo k chybě při načítání adresáře &lt;span class=&#39;dialog-filename&#39;&gt;{0}&lt;/span&gt;. (chyba {1})",
    "READ_DIRECTORY_ENTRIES_ERROR": "Při čtení obsahu složky &lt;span class=&#39;dialog-filename&#39;&gt;{0}&lt;/span&gt; došlo k chybě. (chyba {1})",
    "ERROR_OPENING_FILE_TITLE": "Chyba při otevírání souboru",
    "ERROR_OPENING_FILE": "Při pokusu o otevření souboru &lt;span class=&#39;dialog-filename&#39;&gt;{0}&lt;/span&gt; došlo k chybě. {1}",
    "ERROR_OPENING_FILES": "Při pokusu o otevření následujících souborů došlo k chybě:",
    "ERROR_RELOADING_FILE_TITLE": "Chyba při načítání změn z disku",
    "ERROR_RELOADING_FILE": "Došlo k chybě při načítání souboru &lt;span class=&#39;dialog-filename&#39;&gt;{0}&lt;/span&gt;. {1}",
    "ERROR_SAVING_FILE_TITLE": "Chyba při ukládání souboru",
    "ERROR_SAVING_FILE": "Při pokusu o uložení souboru &lt;span class=&#39;dialog-filename&#39;&gt;{0}&lt;/span&gt; došlo k chybě. {1}",
    "ERROR_RENAMING_FILE_TITLE": "Chyba při přejmenování souboru",
    "ERROR_RENAMING_FILE": "Při pokusu o přejmenování souboru &lt;span class=&#39;dialog-filename&#39;&gt;{0}&lt;/span&gt; došlo k chybě. {1}",
    "ERROR_DELETING_FILE_TITLE": "Chyba při odstraňování souboru",
    "ERROR_DELETING_FILE": "Při pokusu o smazání souboru &lt;span class=&#39;dialog-filename&#39;&gt;{0}&lt;/span&gt; došlo k chybě. {1}",
    "INVALID_FILENAME_TITLE": "Neplatný název souboru",
    "INVALID_FILENAME_MESSAGE": "Název souboru nesmí obsahovat žádná systémem rezervovaná slova, končit tečkami (.) nebo obsahovat některý z následujících znaků: &lt;code class=&#39;emphasized&#39;&gt;{1}&lt;/code&gt;",
    "ENTRY_WITH_SAME_NAME_EXISTS": "Soubor nebo adresář s názvem &lt;span class=&#39;dialog-filename&#39;&gt;{0}&lt;/span&gt; již existuje.",
    "ERROR_CREATING_FILE_TITLE": "Chyba při vytváření souboru",
    "ERROR_CREATING_FILE": "Při pokusu o vytvoření souboru &lt;span class=&#39;dialog-filename&#39;&gt;{1}&lt;/span&gt; došlo k chybě. {2}",
    "ERROR_MIXED_DRAGDROP": "Nelze otevřít složku ve chvíli, kdy se otevírají jiné soubory.",
    "ERROR_KEYMAP_TITLE": "Chyba při čtení uživatelských klávesových zkratek",
    "ERROR_KEYMAP_CORRUPT": "Soubor s nastavením klávesových zkratek není platný soubor typu JSON. Soubor bude otevřen, abyste mohli opravit formát.",
    "ERROR_LOADING_KEYMAP": "Váš soubor s klávesovými zkratkami není platný UTF-8 soubor a nemůže být otevřen",
    "ERROR_RESTRICTED_COMMANDS": "Nemůžete změnit klávesové zkratky následujícím příkazům: {0}",
    "ERROR_RESTRICTED_SHORTCUTS": "Nemůžete změnit tyto klávesové zkratky: {0}",
    "ERROR_MULTIPLE_SHORTCUTS": "Vytváříte více klávesových zkratek pro tyto příkazy: {0}",
    "ERROR_DUPLICATE_SHORTCUTS": "Tyto příkazy mají stejnou klávesovou zkratku: {0}",
    "ERROR_INVALID_SHORTCUTS": "Tyto klávesové zkratky jsou neplatné: {0}",
    "ERROR_NONEXISTENT_COMMANDS": "Vytváříte klávesovou zkratku pro neexistující příkaz: {0}",
    "ERROR_PREFS_CORRUPT_TITLE": "Chyba při čtení nastavení",
    "ERROR_PREFS_CORRUPT": "Soubor s nastavením není platný soubor typu JSON. Soubor bude otevřen, abyste mohli opravit formát. Pro uložení změn budete muset restartovat aplikaci {APP_NAME}.",
    "ERROR_PROJ_PREFS_CORRUPT": "Soubor s preferencemi vašeho projektu neodpovídá validnímu JSON formátu. Tento soubor bude otevřen, abyste mohl formát opravit. K provedení změn bude nutné znovu načíst projekt.",
    "ERROR_IN_BROWSER_TITLE": "Ouha! {APP_NAME} ještě neběží v prohlížeči.",
    "ERROR_IN_BROWSER": "{APP_NAME} je vytvořen v HTML, ale nyní pracuje jako desktopová aplikace, takže ji můžete použít pro úpravu lokálních souborů. Prosím, použijte shell aplikace v repozitáři &lt;b&gt;github.com/adobe/brackets-shell&lt;/b&gt; pro spuštění {APP_NAME}.",
    "ERROR_MAX_FILES_TITLE": "Chyba při indexování souborů",
    "ERROR_MAX_FILES": "Tento projekt obsahuje více než 30.000 souborů. Funkce zpracovávající více souborů mohou být zablokované nebo se mohou chovat jako kdyby byl projekt prázdný. &lt;a href=&#39;https://github.com/adobe/brackets/wiki/Large-Projects&#39;&gt;Čtěte více o práci s obřími projekty&lt;/a&gt;.",
    "ERROR_LAUNCHING_BROWSER_TITLE": "Chyba při spouštění prohlížeče",
    "ERROR_CANT_FIND_CHROME": "Prohlížeč Google Chrome nebyl nalezen. Přesvědčte se, že je nainstalován",
    "ERROR_LAUNCHING_BROWSER": "Došlo k chybě při spouštění prohlížeče. (chyba {0})",
    "LIVE_DEVELOPMENT_ERROR_TITLE": "Živý náhled - chyba",
    "LIVE_DEVELOPMENT_RELAUNCH_TITLE": "Připojování k prohlížeči",
    "LIVE_DEVELOPMENT_ERROR_MESSAGE": "Aby se mohl živý náhled připojit, je třeba restartovat Chrome s povolenou možností vzdálené ladění.&lt;br /&gt;&lt;br /&gt;Chcete restartovat Chrome a povolit vzdálené ladění?&lt;br /&gt;&lt;br /&gt;",
    "LIVE_DEV_LOADING_ERROR_MESSAGE": "Nelze načíst stránku s živým náhledem",
    "LIVE_DEV_NEED_HTML_MESSAGE": "Otevřete HTML soubor pro zobrazení v živém náhledu.",
    "LIVE_DEV_NEED_BASEURL_MESSAGE": "Pro spuštění živého náhledu se vzdáleným souborem, musíte specifikovat URL pro tento projekt.",
    "LIVE_DEV_SERVER_NOT_READY_MESSAGE": "Chyba při spouštění HTTP serveru pro soubory živého náhledu. Prosím, zkuste to znovu.",
    "LIVE_DEVELOPMENT_INFO_TITLE": "Vítejte v živém náhledu!",
    "LIVE_DEVELOPMENT_INFO_MESSAGE": "Živý náhled připojí {APP_NAME} k vašemu prohlížeči. Spustí náhled HTML souboru, který se aktualizuje pokaždé, kdy editujete svůj kód.&lt;br /&gt;&lt;br /&gt;V této verzi {APP_NAME}, živý náhled funguje pouze v &lt;strong&gt;Google Chrome&lt;/strong&gt; a aktualizuje změny v &lt;strong&gt;CSS souborech&lt;/strong&gt;. Změny v HTML nebo JavaScript souborech jsou automaticky načteny, když soubor uložíte.&lt;br /&gt;&lt;br /&gt;(Tato zpráva se zobrazí pouze jednou.)",
    "LIVE_DEVELOPMENT_TROUBLESHOOTING": "Pro více informací navštivte stránku &lt;a href=&#39;{0}&#39; title=&#39;{0}&#39;&gt;řešení problémů s připojením v Živém náhledu&lt;/a&gt;.",
    "LIVE_DEV_STATUS_TIP_NOT_CONNECTED": "Živý náhled",
    "LIVE_DEV_STATUS_TIP_PROGRESS1": "Živý náhled: Připojování…",
    "LIVE_DEV_STATUS_TIP_PROGRESS2": "Živý náhled: Spouštění…",
    "LIVE_DEV_STATUS_TIP_CONNECTED": "Zrušit živý náhled",
    "LIVE_DEV_STATUS_TIP_OUT_OF_SYNC": "Živý náhled (uložte soubor)",
    "LIVE_DEV_STATUS_TIP_SYNC_ERROR": "Živý náhled (neaktualizováno kvůli chybě v syntaxi)",
    "LIVE_DEV_DETACHED_REPLACED_WITH_DEVTOOLS": "Živý náhled byl zrušen, protože byly otevřeny vývojářské nástroje prohlížeče",
    "LIVE_DEV_DETACHED_TARGET_CLOSED": "Živý náhled byl zrušen, protože dokument byl zavřen v prohlížeči",
    "LIVE_DEV_NAVIGATED_AWAY": "Živý náhled byl zrušen, protože prohlížeč přešel na stránku, která není součástí projektu",
    "LIVE_DEV_CLOSED_UNKNOWN_REASON": "Živý náhled byl zrušen z neznámého důvodu ({0})",
    "SAVE_CLOSE_TITLE": "Uložit změny",
    "SAVE_CLOSE_MESSAGE": "Chcete uložit změny v souboru &lt;span class=&#39;dialog-filename&#39;&gt;{0}&lt;/span&gt;?",
    "SAVE_CLOSE_MULTI_MESSAGE": "Chcete uložit změny v následujících souborech?",
    "EXT_MODIFIED_TITLE": "Externí změny",
    "CONFIRM_FOLDER_DELETE_TITLE": "Potvrdit smazání",
    "CONFIRM_FOLDER_DELETE": "Opravdu chcete smazat složku &lt;span class=&#39;dialog-filename&#39;&gt;{0}&lt;/span&gt;?",
    "FILE_DELETED_TITLE": "Soubor byl smazán",
    "EXT_MODIFIED_WARNING": "Soubor &lt;span class=&#39;dialog-filename&#39;&gt;{0}&lt;/span&gt; byl změněn na disku mimo aplikaci {APP_NAME}.&lt;br /&gt;&lt;br /&gt;Chcete uložit soubor a přepsat tyto změny?",
    "EXT_MODIFIED_MESSAGE": "Soubor &lt;span class=&#39;dialog-filename&#39;&gt;{0}&lt;/span&gt; byl změněn na disku mimo aplikaci {APP_NAME}, ale také obsahuje neuložené změny v aplikaci {APP_NAME}.&lt;br /&gt;&lt;br /&gt;Kterou verzi chcete zachovat?",
    "EXT_DELETED_MESSAGE": "Soubor &lt;span class=&#39;dialog-filename&#39;&gt;{0}&lt;/span&gt; byl změněn na disku mimo aplikaci {APP_NAME}, ale také obsahuje neuložené změny v aplikaci {APP_NAME}.&lt;br /&gt;&lt;br /&gt;Chcete zachovat vaše změny?",
    "DONE": "Dokončit",
    "OK": "OK",
    "CANCEL": "Zrušit",
    "DONT_SAVE": "Neukládat",
    "SAVE": "Uložit",
    "SAVE_AS": "Uložit jako…",
    "SAVE_AND_OVERWRITE": "Přepsat",
    "DELETE": "Smazat",
    "BUTTON_YES": "Ano",
    "BUTTON_NO": "Ne",
    "FIND_MATCH_INDEX": "{0} z {1}",
    "FIND_NO_RESULTS": "Žádné výsledky",
    "FIND_QUERY_PLACEHOLDER": "Najít…",
    "REPLACE_PLACEHOLDER": "Nahradit s…",
    "BUTTON_REPLACE_ALL": "Vše…",
    "BUTTON_REPLACE_ALL_IN_FILES": "Nahradit…",
    "BUTTON_REPLACE": "Nahradit",
    "BUTTON_NEXT": "▶",
    "BUTTON_PREV": "◀",
    "BUTTON_NEXT_HINT": "Další shoda",
    "BUTTON_PREV_HINT": "Předchozí shoda",
    "BUTTON_CASESENSITIVE_HINT": "Rozlišovat velká a malá písmena",
    "BUTTON_REGEXP_HINT": "Regulární výraz",
    "REPLACE_WITHOUT_UNDO_WARNING_TITLE": "Nahradit bez možnosti vrátit změny",
    "REPLACE_WITHOUT_UNDO_WARNING": "Protože musí být změněno více než {0} souborů, {APP_NAME} změní neotevřené soubory na disku.&lt;br /&gt;Nebude možné vrátit změny v těchto souborech.",
    "BUTTON_REPLACE_WITHOUT_UNDO": "Nahradit bez možnosti vrátit změny",
    "OPEN_FILE": "Otevřít soubor",
    "SAVE_FILE_AS": "Uložit soubor",
    "CHOOSE_FOLDER": "Vybrat složku",
    "RELEASE_NOTES": "Poznámky k verzi",
    "NO_UPDATE_TITLE": "Vše je aktuální!",
    "NO_UPDATE_MESSAGE": "Verze {APP_NAME} je aktuální.",
    "FIND_REPLACE_TITLE_LABEL": "Nahradit",
    "FIND_REPLACE_TITLE_WITH": "s",
    "FIND_TITLE_LABEL": "Nalezeno",
    "FIND_TITLE_SUMMARY": "&amp;mdash; {0} {1} {2} v {3}",
    "FIND_NUM_FILES": "{0} {1}",
    "FIND_IN_FILES_SCOPED": "v &lt;span class=&#39;dialog-filename&#39;&gt;{0}&lt;/span&gt;",
    "FIND_IN_FILES_NO_SCOPE": "v projektu",
    "FIND_IN_FILES_ZERO_FILES": "Filtr vyloučil všechny soubory {0}",
    "FIND_IN_FILES_FILE": "souboru",
    "FIND_IN_FILES_FILES": "souborech",
    "FIND_IN_FILES_MATCH": "výsledek",
    "FIND_IN_FILES_MATCHES": "výsledků",
    "FIND_IN_FILES_MORE_THAN": "více než ",
    "FIND_IN_FILES_PAGING": "{0}&amp;mdash;{1}",
    "FIND_IN_FILES_FILE_PATH": "Soubor &lt;span class=&#39;dialog-filename&#39;&gt;{0}&lt;/span&gt; ve složce &lt;span class=&#39;dialog-path&#39;&gt;{1}&lt;/span&gt;",
    "FIND_IN_FILES_EXPAND_COLLAPSE": "Ctrl/Cmd klik pro rozbalení/sbalení všeho",
    "REPLACE_IN_FILES_ERRORS_TITLE": "Nahradit chyby",
    "REPLACE_IN_FILES_ERRORS": "Následující soubory nebyly změněny, protože se změnily po hledání nebo do nich nelze zapisovat.",
    "ERROR_FETCHING_UPDATE_INFO_TITLE": "Chyba při získávání informací o aktualizaci",
    "ERROR_FETCHING_UPDATE_INFO_MSG": "Nelze získat aktualizace. Ujistěte se, že máte připojení k internetu a zkuste to znovu.",
    "NEW_FILE_FILTER": "Nová řada vyloučených souborů…",
    "CLEAR_FILE_FILTER": "Nevylučovat soubory",
    "NO_FILE_FILTER": "Vyloučit soubory…",
    "EXCLUDE_FILE_FILTER": "Vyloučit {0}",
    "EDIT_FILE_FILTER": "Upravit…",
    "FILE_FILTER_DIALOG": "Upravit filtr",
    "FILE_FILTER_INSTRUCTIONS": "Vyloučit soubory a složky, které obsahují jakýkoliv z následujících řetězců / podřetězců nebo &lt;a href=&#39;{0}&#39; title=&#39;{0}&#39;&gt;vzorků&lt;/a&gt;. Vložte každý řetězec na nový řádek.",
    "FILTER_NAME_PLACEHOLDER": "Pojmenujte řadu vyloučených souborů (nepovinné)",
    "FILE_FILTER_CLIPPED_SUFFIX": "a {0} více",
    "FILTER_COUNTING_FILES": "Počítání souborů…",
    "FILTER_FILE_COUNT": "Povolit {0} z {1} souborů {2}",
    "FILTER_FILE_COUNT_ALL": "Povolit všechny {0} soubory {1}",
    "ERROR_QUICK_EDIT_PROVIDER_NOT_FOUND": "Rychlá úprava není k dispozici pro aktuální pozici kurzoru",
    "ERROR_CSSQUICKEDIT_BETWEENCLASSES": "Rychlá úprava CSS: umístěte kurzor na jeden název třídy",
    "ERROR_CSSQUICKEDIT_CLASSNOTFOUND": "Rychlá úprava CSS: nekompletní atribut třídy",
    "ERROR_CSSQUICKEDIT_IDNOTFOUND": "Rychlá úprava CSS: nekompletní atribut id",
    "ERROR_CSSQUICKEDIT_UNSUPPORTEDATTR": "Rychlá úprava CSS: umístěte kurzor do značky, třídy nebo id",
    "ERROR_TIMINGQUICKEDIT_INVALIDSYNTAX": "Rychlá úprava načasování funkce CSS: neplatná syntaxe",
    "ERROR_JSQUICKEDIT_FUNCTIONNOTFOUND": "Rychlá úprava JS: umístěte kurzor do názvu funkce",
    "ERROR_QUICK_DOCS_PROVIDER_NOT_FOUND": "Rychlá úprava dokumentů není k dispozici pro aktuální pozici kurzoru",
    "PROJECT_LOADING": "Načítání…",
    "UNTITLED": "Nový",
    "WORKING_FILES": "Pracovní soubory",
    "TOP": "Nahoře",
    "BOTTOM": "Dole",
    "LEFT": "Vlevo",
    "RIGHT": "Vpravo",
    "CMD_SPLITVIEW_NONE": "Bez rozdělení",
    "CMD_SPLITVIEW_VERTICAL": "Vertikální rozdělení",
    "CMD_SPLITVIEW_HORIZONTAL": "Horizontální rozdělení",
    "SPLITVIEW_MENU_TOOLTIP": "Rozdělit editor horizontálně nebo vertikálně",
    "GEAR_MENU_TOOLTIP": "Nastavit pracovní plochu",
    "SPLITVIEW_INFO_TITLE": "Již otevřen",
    "SPLITVIEW_MULTIPANE_WARNING": "Soubor je již otevřen v jiném okně. {APP_NAME} bude brzy podporovat otevírání stejného souboru ve více oknech. Do té doby bude soubor zobrazen v již otevřeném okně.&lt;br /&gt;&lt;br /&gt;(Tuto zprávu uvidíte pouze jednou.)",
    "KEYBOARD_CTRL": "Ctrl",
    "KEYBOARD_SHIFT": "Shift",
    "KEYBOARD_SPACE": "Space",
    "STATUSBAR_CURSOR_POSITION": "Řádek {0}, Sloupec {1}",
    "STATUSBAR_SELECTION_CH_SINGULAR": " — Vybrán {0} sloupec",
    "STATUSBAR_SELECTION_CH_PLURAL": " — Vybrány {0} sloupce",
    "STATUSBAR_SELECTION_LINE_SINGULAR": " — Vybrán {0} řádek",
    "STATUSBAR_SELECTION_LINE_PLURAL": " — Vybrány {0} řádky",
    "STATUSBAR_SELECTION_MULTIPLE": " — {0} Vybráno",
    "STATUSBAR_INDENT_TOOLTIP_SPACES": "Přepnout odsazení na mezery",
    "STATUSBAR_INDENT_TOOLTIP_TABS": "Přepnout odsazení na tabulátory",
    "STATUSBAR_INDENT_SIZE_TOOLTIP_SPACES": "Změnit počet mezer použitých pro odsazení",
    "STATUSBAR_INDENT_SIZE_TOOLTIP_TABS": "Změnit šířku tabulátoru",
    "STATUSBAR_SPACES": "Mezery:",
    "STATUSBAR_TAB_SIZE": "Velikost tabulátoru:",
    "STATUSBAR_LINE_COUNT_SINGULAR": "Řádek: {0}",
    "STATUSBAR_LINE_COUNT_PLURAL": "Řádky: {0}",
    "STATUSBAR_USER_EXTENSIONS_DISABLED": "Doplňky zakázány",
    "STATUSBAR_INSERT": "INS",
    "STATUSBAR_OVERWRITE": "OVR",
    "STATUSBAR_INSOVR_TOOLTIP": "Klikněte pro přepnutí kurzoru mezi módem Insert (INS) a Overwrite (OVR)",
    "STATUSBAR_LANG_TOOLTIP": "Klikněte pro změnu typu souboru",
    "STATUSBAR_CODE_INSPECTION_TOOLTIP": "{0}. Klikněte pro zapnutí panelu zpráv.",
    "STATUSBAR_DEFAULT_LANG": "(výchozí)",
    "STATUSBAR_SET_DEFAULT_LANG": "Nastavit jako výchozí pro .{0} soubory",
    "ERRORS_PANEL_TITLE_MULTIPLE": "{0} chyb",
    "SINGLE_ERROR": "1 {0} chyba",
    "MULTIPLE_ERRORS": "{1} {0} chyby",
    "NO_ERRORS": "Žádné {0} chyby - dobrá práce!",
    "NO_ERRORS_MULTIPLE_PROVIDER": "Žádné chyby nenalezeny - dobrá práce!",
    "LINT_DISABLED": "Lintování je vypnuto",
    "NO_LINT_AVAILABLE": "Žádný linter není dostupný pro {0}",
    "NOTHING_TO_LINT": "Nic k lintování",
    "LINTER_TIMED_OUT": "{0} - vypršel časový limit po uplynutí {1} ms",
    "LINTER_FAILED": "{0} byl(a) ukončen(a) s chybou: {1}",
    "FILE_MENU": "Soubor",
    "CMD_FILE_NEW_UNTITLED": "Nový",
    "CMD_FILE_NEW": "Nový soubor",
    "CMD_FILE_NEW_FOLDER": "Nová složka",
    "CMD_FILE_OPEN": "Otevřít…",
    "CMD_ADD_TO_WORKING_SET": "Přidat k pracovní sadě",
    "CMD_OPEN_DROPPED_FILES": "Otevřít opuštěné soubory",
    "CMD_OPEN_FOLDER": "Otevřít složku…",
    "CMD_FILE_CLOSE": "Zavřít",
    "CMD_FILE_CLOSE_ALL": "Zavřít vše",
    "CMD_FILE_CLOSE_LIST": "Zavřít seznam",
    "CMD_FILE_CLOSE_OTHERS": "Zavřít ostatní",
    "CMD_FILE_CLOSE_ABOVE": "Zavřít ostatní výše",
    "CMD_FILE_CLOSE_BELOW": "Zavřít ostatní níže",
    "CMD_FILE_SAVE": "Uložit",
    "CMD_FILE_SAVE_ALL": "Uložit vše",
    "CMD_FILE_SAVE_AS": "Uložit jako…",
    "CMD_LIVE_FILE_PREVIEW": "Živý náhled",
    "CMD_TOGGLE_LIVE_PREVIEW_MB_MODE": "Experimentální živý náhled",
    "CMD_RELOAD_LIVE_PREVIEW": "Vynutit obnovení živého náhledu",
    "CMD_PROJECT_SETTINGS": "Nastavení projektu…",
    "CMD_FILE_RENAME": "Přejmenovat",
    "CMD_FILE_DELETE": "Smazat",
    "CMD_INSTALL_EXTENSION": "Instalovat doplňky…",
    "CMD_EXTENSION_MANAGER": "Správce doplňků…",
    "CMD_FILE_REFRESH": "Obnovit",
    "CMD_QUIT": "Konec",
    "CMD_EXIT": "Konec",
    "EDIT_MENU": "Úpravy",
    "CMD_UNDO": "Zpět",
    "CMD_REDO": "Znovu",
    "CMD_CUT": "Vyjmout",
    "CMD_COPY": "Kopírovat",
    "CMD_PASTE": "Vložit",
    "CMD_SELECT_ALL": "Vybrat vše",
    "CMD_SELECT_LINE": "Vybrat řádek",
    "CMD_SPLIT_SEL_INTO_LINES": "Rozdělit výběr na řádky",
    "CMD_ADD_CUR_TO_NEXT_LINE": "Přidat kurzor na další řádek",
    "CMD_ADD_CUR_TO_PREV_LINE": "Přidat kurzor na předcházející řádek",
    "CMD_INDENT": "Odsadit",
    "CMD_UNINDENT": "Vrátit odsazení",
    "CMD_DUPLICATE": "Duplikovat",
    "CMD_DELETE_LINES": "Smazat řádek",
    "CMD_COMMENT": "Řádkový komentář",
    "CMD_BLOCK_COMMENT": "Blokový komentář",
    "CMD_LINE_UP": "Posunout řádek nahoru",
    "CMD_LINE_DOWN": "Posunout řádek dolů",
    "CMD_OPEN_LINE_ABOVE": "O řádek výše",
    "CMD_OPEN_LINE_BELOW": "O řádek níže",
    "CMD_TOGGLE_CLOSE_BRACKETS": "Uzavírat závorky",
    "CMD_SHOW_CODE_HINTS": "Zobrazit nápovědy",
    "FIND_MENU": "Najít",
    "CMD_FIND": "Najít",
    "CMD_FIND_NEXT": "Najít další",
    "CMD_FIND_PREVIOUS": "Najít předchozí",
    "CMD_FIND_ALL_AND_SELECT": "Najít vše a vybrat",
    "CMD_ADD_NEXT_MATCH": "Přidat další shodu do výběru",
    "CMD_SKIP_CURRENT_MATCH": "Přeskočit a přidat další shodu do výběru",
    "CMD_FIND_IN_FILES": "Najít v souborech",
    "CMD_FIND_IN_SUBTREE": "Najít v…",
    "CMD_REPLACE": "Nahradit",
    "CMD_REPLACE_IN_FILES": "Nahradit v souborech",
    "CMD_REPLACE_IN_SUBTREE": "Nahradit v…",
    "VIEW_MENU": "Zobrazit",
    "CMD_HIDE_SIDEBAR": "Skrýt boční menu",
    "CMD_SHOW_SIDEBAR": "Zobrazit boční menu",
    "CMD_INCREASE_FONT_SIZE": "Zvětšit velikost písma",
    "CMD_DECREASE_FONT_SIZE": "Zmenšit velikost písma",
    "CMD_RESTORE_FONT_SIZE": "Obnovit velikost písma",
    "CMD_SCROLL_LINE_UP": "Posunout o řádek nahoru",
    "CMD_SCROLL_LINE_DOWN": "Posunout o řádek dolů",
    "CMD_TOGGLE_LINE_NUMBERS": "Čísla řádků",
    "CMD_TOGGLE_ACTIVE_LINE": "Zvýraznit aktivní řádek",
    "CMD_TOGGLE_WORD_WRAP": "Zalomit řádky",
    "CMD_LIVE_HIGHLIGHT": "Živé zvýraznění",
    "CMD_VIEW_TOGGLE_INSPECTION": "Lintovat soubory při uložení",
    "CMD_WORKINGSET_SORT_BY_ADDED": "Řadit podle data přidání",
    "CMD_WORKINGSET_SORT_BY_NAME": "Řadit podle jména",
    "CMD_WORKINGSET_SORT_BY_TYPE": "Řadit podle typu",
    "CMD_WORKING_SORT_TOGGLE_AUTO": "Automatické řazení",
    "CMD_THEMES": "Motivy…",
    "NAVIGATE_MENU": "Navigace",
    "CMD_QUICK_OPEN": "Rychle otevřít",
    "CMD_GOTO_LINE": "Přejít na řádek",
    "CMD_GOTO_DEFINITION": "Přejít na definici",
    "CMD_GOTO_FIRST_PROBLEM": "Přejít na první chybu/varování",
    "CMD_TOGGLE_QUICK_EDIT": "Rychlá úprava",
    "CMD_TOGGLE_QUICK_DOCS": "Rychlé dokumenty",
    "CMD_QUICK_EDIT_PREV_MATCH": "Předchozí shoda",
    "CMD_QUICK_EDIT_NEXT_MATCH": "Další shoda",
    "CMD_CSS_QUICK_EDIT_NEW_RULE": "Nové pravidlo",
    "CMD_NEXT_DOC": "Další dokument",
    "CMD_PREV_DOC": "Předchozí dokument",
    "CMD_SHOW_IN_TREE": "Zobrazit stromovou strukturu",
    "CMD_SHOW_IN_EXPLORER": "Zobrazit v průzkumníkovi",
    "CMD_SHOW_IN_FINDER": "Zobrazit ve vyhledávači",
    "CMD_SHOW_IN_OS": "Zobrazit v OS",
    "HELP_MENU": "Nápověda",
    "CMD_CHECK_FOR_UPDATE": "Zkontrolovat aktualizace",
    "CMD_HOW_TO_USE_BRACKETS": "Jak používat {APP_NAME}",
    "CMD_SUPPORT": "{APP_NAME} Podpora",
    "CMD_SUGGEST": "Navrhněte funkci",
    "CMD_RELEASE_NOTES": "Poznámky k verzi",
    "CMD_GET_INVOLVED": "Zapojte se",
    "CMD_SHOW_EXTENSIONS_FOLDER": "Zobrazit složku s doplňky",
    "CMD_HEALTH_DATA_STATISTICS": "Hlášení o zdraví",
    "CMD_HOMEPAGE": "Domovská stránka {APP_TITLE}",
    "CMD_TWITTER": "{TWITTER_NAME} na Twitteru",
    "CMD_ABOUT": "O aplikaci {APP_TITLE}",
    "CMD_OPEN_PREFERENCES": "Otevřít soubor s preferencemi",
    "CMD_OPEN_KEYMAP": "Otevřít uživatelské klávesové zkratky",
    "EXPERIMENTAL_BUILD": "experimentální sestavení",
    "RELEASE_BUILD": "sestavení",
    "DEVELOPMENT_BUILD": "vývojové sestavení",
    "RELOAD_FROM_DISK": "Načíst z disku",
    "KEEP_CHANGES_IN_EDITOR": "Ponechat změny v editoru",
    "CLOSE_DONT_SAVE": "Zavřít (neukládat)",
    "RELAUNCH_CHROME": "Restartovat Chrome",
    "ABOUT": "O aplikaci",
    "CLOSE": "Zavřít",
    "ABOUT_TEXT_LINE1": "Vydání {VERSION_MAJOR}.{VERSION_MINOR} {BUILD_TYPE} {VERSION}",
    "ABOUT_TEXT_BUILD_TIMESTAMP": "vytvořeno: ",
    "ABOUT_TEXT_LINE3": "Oznámení, podmínky týkající se software třetích stran jsou umístěny na stránce &lt;a href=&#39;{ADOBE_THIRD_PARTY}&#39;&gt;{ADOBE_THIRD_PARTY}&lt;/a&gt; a začleněny prostřednictvím odkazu zde.",
    "ABOUT_TEXT_LINE4": "Dokumentace a zdrojový kód na stránce &lt;a href=&#39;https://github.com/adobe/brackets/&#39;&gt;https://github.com/adobe/brackets/&lt;/a&gt;.",
    "ABOUT_TEXT_LINE5": "Vytvořeno s ❤ a pomocí JavaScriptu těmito lidmi:",
    "ABOUT_TEXT_LINE6": "Mnoho lidí (ale momentálně máme problém s načítáním dat).",
    "ABOUT_TEXT_WEB_PLATFORM_DOCS": "Web Platform Docs a Web Platform logo využívají licenci Creative Commons Attribution, &lt;a href=&#39;{WEB_PLATFORM_DOCS_LICENSE}&#39;&gt;CC-BY 3.0 Unported&lt;/a&gt;.",
    "UPDATE_NOTIFICATION_TOOLTIP": "Je dostupná nová verze {APP_NAME}! Klikněte zde pro více informací.",
    "UPDATE_AVAILABLE_TITLE": "Dostupná aktualizace",
    "UPDATE_MESSAGE": "Nová verze {APP_NAME} je dostupná. Seznam některých vylepšení:",
    "GET_IT_NOW": "Stáhnout!",
    "PROJECT_SETTINGS_TITLE": "Nastavení projektu: {0}",
    "PROJECT_SETTING_BASE_URL": "URL Živého náhledu",
    "PROJECT_SETTING_BASE_URL_HINT": "(nechte prázdné pro URL souboru)",
    "BASEURL_ERROR_INVALID_PROTOCOL": "{0} protokol není podporován živým náhledem&amp;mdash;prosím, použijte http: nebo https: .",
    "BASEURL_ERROR_SEARCH_DISALLOWED": "URL nemůže obsahovat výrazy pro hledání jako &quot;{0}&quot;.",
    "BASEURL_ERROR_HASH_DISALLOWED": "URL nemůže obsahovat znaky jako &quot;{0}&quot;.",
    "BASEURL_ERROR_INVALID_CHAR": "Zvláštní znaky jako &#39;{0}&#39; musí být %-enkódovány.",
    "BASEURL_ERROR_UNKNOWN_ERROR": "Neznámá chyba při zpracování URL",
    "EMPTY_VIEW_HEADER": "&lt;em&gt;Otevřete soubor, zatímco tento panel má fokus&lt;/em&gt;",
    "CURRENT_THEME": "Aktuální motiv",
    "USE_THEME_SCROLLBARS": "Použít posuvníky motivu",
    "FONT_SIZE": "Velikost písma",
    "FONT_FAMILY": "Rodina písma",
    "THEMES_SETTINGS": "Nastavení motivů",
    "BUTTON_NEW_RULE": "Nové pravidlo",
    "INSTALL": "Instalovat",
    "UPDATE": "Aktualizovat",
    "REMOVE": "Odstranit",
    "OVERWRITE": "Přepsat",
    "CANT_REMOVE_DEV": "Doplněk ve složce &quot;dev&quot; musí být smazán manuálně.",
    "CANT_UPDATE": "Aktualizace není kompatibilní s touto verzí {APP_NAME}.",
    "CANT_UPDATE_DEV": "Doplňky ve složce &quot;dev&quot; nemohou být aktualizovány automaticky.",
    "INSTALL_EXTENSION_TITLE": "Instalovat doplněk",
    "UPDATE_EXTENSION_TITLE": "Aktualizovat doplněk",
    "INSTALL_EXTENSION_LABEL": "URL adresa doplňku",
    "INSTALL_EXTENSION_HINT": "URL adresa zip archivu nebo GitHub repozitáře",
    "INSTALLING_FROM": "Instalace doplňku z {0}…",
    "INSTALL_SUCCEEDED": "Instalace byla úspěšná!",
    "INSTALL_FAILED": "Instalace se nezdařila.",
    "CANCELING_INSTALL": "Rušení instalace…",
    "CANCELING_HUNG": "Rušení instalace trvá dlouho. Mohlo dojít k interní chybě.",
    "INSTALL_CANCELED": "Instalace zrušena.",
    "VIEW_COMPLETE_DESCRIPTION": "Zobrazit úplný popis",
    "VIEW_TRUNCATED_DESCRIPTION": "Zobrazit zkrácený popis",
    "INVALID_ZIP_FILE": "Stažený soubor není platný zip soubor.",
    "INVALID_PACKAGE_JSON": "Package.json balíček není platný (chyba byla: {0}).",
    "MISSING_PACKAGE_NAME": "Package.json balíček nespecifikuje jméno souboru.",
    "BAD_PACKAGE_NAME": "{0} je neplatné jméno balíčku.",
    "MISSING_PACKAGE_VERSION": "Package.json balíček nespecifikuje verzi souboru.",
    "INVALID_VERSION_NUMBER": "Balíček verze ({0}) je neplatný.",
    "INVALID_BRACKETS_VERSION": "Řetězec kompatibility {0} pro {APP_NAME} je neplatný.",
    "DISALLOWED_WORDS": "Slova {1} nejsou povolena v {0} poli.",
    "API_NOT_COMPATIBLE": "Doplněk není kompatibilní s touto verzí {APP_NAME}. Naleznete jej ve složce disabled extensions.",
    "MISSING_MAIN": "Balíček neobsahuje soubor main.js.",
    "EXTENSION_ALREADY_INSTALLED": "Instalace tohoto balíčku přepíše již nainstalovaný doplněk. Chcete přepsat starý doplněk?",
    "EXTENSION_SAME_VERSION": "Tento balíček je stejná verze jako ta, kterou již máte nainstalovanou. Chcete přepsat existující doplněk?",
    "EXTENSION_OLDER_VERSION": "Tento balíček je verze {0}, která je starší než současně nainstalovaná verze ({1}). Chcete přepsat existující doplněk?",
    "DOWNLOAD_ID_IN_USE": "Interní chyba: ID stahování se již používá.",
    "NO_SERVER_RESPONSE": "Nelze se připojit na server.",
    "BAD_HTTP_STATUS": "Soubor nebyl nalezen (HTTP {0}).",
    "CANNOT_WRITE_TEMP": "Nelze uložit do dočasných souborů.",
    "ERROR_LOADING": "Při spuštění doplňku došlo k chybě.",
    "MALFORMED_URL": "URL adresa je neplatná. Ujistěte se, že jste adresu zadali správně.",
    "UNSUPPORTED_PROTOCOL": "URL adresa musí být http nebo https.",
    "UNKNOWN_ERROR": "Neznámá chyba.",
    "EXTENSION_MANAGER_TITLE": "Správce doplňků",
    "EXTENSION_MANAGER_ERROR_LOAD": "Nelze získat přístup k registru doplňků. Prosím, zkuste to znovu později.",
    "INSTALL_EXTENSION_DRAG": "Přetáhněte .zip zde nebo",
    "INSTALL_EXTENSION_DROP": "Pusťte .zip pro instalaci",
    "INSTALL_EXTENSION_DROP_ERROR": "Instalace/aktualizace byla zrušena kvůli následujících chyb:",
    "INSTALL_FROM_URL": "Instalovat z URL…",
    "INSTALL_EXTENSION_VALIDATING": "Ověření…",
    "EXTENSION_AUTHOR": "Autor",
    "EXTENSION_DATE": "Datum",
    "EXTENSION_INCOMPATIBLE_NEWER": "Tento doplněk požaduje novější verzi {APP_NAME}.",
    "EXTENSION_INCOMPATIBLE_OLDER": "Tento doplněk funguje pouze ve starší verzi {APP_NAME}.",
    "EXTENSION_LATEST_INCOMPATIBLE_NEWER": "Verze {0} tohoto doplňku vyžaduje novější verzi {APP_NAME}. Můžete si ale nainstalovat dřívější verzi {1}.",
    "EXTENSION_LATEST_INCOMPATIBLE_OLDER": "Verze {0} tohoto doplňku funguje pouze se starší verzí {APP_NAME}. Můžete si ale nainstalovat dřívější verzi {1}.",
    "EXTENSION_NO_DESCRIPTION": "Bez popisu",
    "EXTENSION_MORE_INFO": "Více informací...",
    "EXTENSION_ERROR": "Chyba doplňku",
    "EXTENSION_KEYWORDS": "Klíčová slova",
    "EXTENSION_TRANSLATED_USER_LANG": "Přeloženo do {0} jazyků, včetně vašeho",
    "EXTENSION_TRANSLATED_GENERAL": "Přeloženo do {0} jazyků",
    "EXTENSION_TRANSLATED_LANGS": "Tento doplněk byl přeložen do těchto jazyků: {0}",
    "EXTENSION_INSTALLED": "Nainstalováno",
    "EXTENSION_UPDATE_INSTALLED": "Aktualizace doplňku byla stažena a bude nainstalována při ukončení aplikace {APP_NAME}.",
    "EXTENSION_SEARCH_PLACEHOLDER": "Hledat",
    "EXTENSION_MORE_INFO_LINK": "Více",
    "BROWSE_EXTENSIONS": "Procházet doplňky",
    "EXTENSION_MANAGER_REMOVE": "Odstranit doplněk",
    "EXTENSION_MANAGER_REMOVE_ERROR": "Chyba při odstraňování jednoho nebo více doplňků: {0}. {APP_NAME} bude stále ukončen.",
    "EXTENSION_MANAGER_UPDATE": "Aktualizovat doplněk",
    "EXTENSION_MANAGER_UPDATE_ERROR": "Nelze aktualizovat jeden nebo více doplňků: {0}. Aplikace {APP_NAME} bude ukončena.",
    "MARKED_FOR_REMOVAL": "Označeno pro odstranění",
    "UNDO_REMOVE": "Zpět",
    "MARKED_FOR_UPDATE": "Označeno pro aktualizaci",
    "UNDO_UPDATE": "Zpět",
    "CHANGE_AND_RELOAD_TITLE": "Změnit doplňky",
    "CHANGE_AND_RELOAD_MESSAGE": "Pro aktualizaci nebo odstranění označených doplňků je třeba restartovat aplikaci {APP_NAME}. Budete vyzváni k uložení změn.",
    "REMOVE_AND_RELOAD": "Odstranit doplňky a restartovat",
    "CHANGE_AND_RELOAD": "Změnit doplňky a restartovat",
    "UPDATE_AND_RELOAD": "Aktualizovat doplňky a restartovat",
    "PROCESSING_EXTENSIONS": "Zpracování změn doplňku…",
    "EXTENSION_NOT_INSTALLED": "Doplněk {0} nemohl být odstraněn, protože nebyl nainstalován.",
    "NO_EXTENSIONS": "Žádný doplněk ještě nebyl nainstalován.&lt;br&gt;Klikněte na tlačítko Instalovat z URL pro zahájení instalace.",
    "NO_EXTENSION_MATCHES": "Žádný doplněk neodpovídá hledání.",
    "REGISTRY_SANITY_CHECK_WARNING": "POZNÁMKA: Tyto doplňky mohou pocházet od jiných autorů než {APP_NAME}. Buďte opatrní při instalaci doplňků z neznámých zdrojů.",
    "EXTENSIONS_INSTALLED_TITLE": "Nainstalované",
    "EXTENSIONS_AVAILABLE_TITLE": "Dostupné",
    "EXTENSIONS_THEMES_TITLE": "Motivy",
    "EXTENSIONS_UPDATES_TITLE": "Aktualizace",
    "INLINE_EDITOR_NO_MATCHES": "Žádné dostupné shody.",
    "INLINE_EDITOR_HIDDEN_MATCHES": "Všechny shody jsou sbalené. Pro prohlédnutí shod rozbalte soubory zobrazené vpravo.",
    "CSS_QUICK_EDIT_NO_MATCHES": "Neexistují žádná CSS pravidla odpovídající vašemu výběru.&lt;br&gt;Pro vytvoření pravidla klikněte na &quot;Nové pravidlo&quot;.",
    "CSS_QUICK_EDIT_NO_STYLESHEETS": "Neexistují žádné soubory s kaskádovými styly ve vašem projektu.&lt;br&gt;Vytvořte nový soubor pro přidání CSS pravidel.",
    "IMAGE_VIEWER_LARGEST_ICON": "největší",
    "UNIT_PIXELS": "pixely",
    "DEBUG_MENU": "Nástroje",
    "ERRORS": "Chyby",
    "CMD_SHOW_DEV_TOOLS": "Zobrazit nástroje pro vývojáře",
    "CMD_REFRESH_WINDOW": "Restartovat {APP_NAME}",
    "CMD_RELOAD_WITHOUT_USER_EXTS": "Restartovat bez doplňků",
    "CMD_NEW_BRACKETS_WINDOW": "Nové okno {APP_NAME}",
    "CMD_LAUNCH_SCRIPT_MAC": "Nainstalovat zástupce do příkazové řádky",
    "CMD_SWITCH_LANGUAGE": "Změnit jazyk",
    "CMD_RUN_UNIT_TESTS": "Spustit testy",
    "CMD_SHOW_PERF_DATA": "Zobrazit údaje o výkonnosti",
    "CMD_ENABLE_NODE_DEBUGGER": "Povolit Node Debugger",
    "CMD_LOG_NODE_STATE": "Uložit stav Node do konzole",
    "CMD_RESTART_NODE": "Restartovat Node",
    "CMD_SHOW_ERRORS_IN_STATUS_BAR": "Zobrazit chyby ve stavovém řádku",
    "CMD_OPEN_BRACKETS_SOURCE": "Otevřít zdroj {APP_NAME}",
    "CREATING_LAUNCH_SCRIPT_TITLE": "Zástupce {APP_NAME} v příkazové řádce",
    "ERROR_CREATING_LAUNCH_SCRIPT": "Při instalaci zástupce do příkazové řádky se vyskytla chyba. Prosím vyzkoušejte řešení &lt;a href=&#39;https://github.com/adobe/brackets/wiki/Command-Line-Arguments#troubleshooting&#39;&gt;na této stránce&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;Důvod: {0}",
    "ERROR_CLTOOLS_RMFAILED": "Nelze odstranit existující symbolický odkaz na &lt;code&gt;/usr/local/bin/brackets&lt;/code&gt;.",
    "ERROR_CLTOOLS_MKDIRFAILED": "Nelze vytvořit složku &lt;code&gt;/usr/local/bin&lt;/code&gt;.",
    "ERROR_CLTOOLS_LNFAILED": "Nelze vytvořit symbolický odkaz na &lt;code&gt;/usr/local/bin/brackets&lt;/code&gt;.",
    "ERROR_CLTOOLS_SERVFAILED": "Vnitřní chyba.",
    "ERROR_CLTOOLS_NOTSUPPORTED": "V tomto operačním systému nelze vytvořit zástupce do příkazové řádky.",
    "LAUNCH_SCRIPT_CREATE_SUCCESS": "Hotovo! Nyní můžete jednoduše spustit {APP_NAME} z příkazové řádky: příkazem &lt;code&gt;brackets myFile.txt&lt;/code&gt; otevřete soubor a příkazem &lt;code&gt;brackets myFolder&lt;/code&gt; změníte projekt. &lt;br/&gt;&lt;br/&gt;&lt;a href=&#39;https://github.com/adobe/brackets/wiki/Command-Line-Arguments&#39;&gt;Na této stránce zjistíte více&lt;/a&gt; o používání {APP_NAME} z příkazové řádky.",
    "LANGUAGE_TITLE": "Změnit jazyk",
    "LANGUAGE_MESSAGE": "Prosím, vyberte jazyk ze seznamu:",
    "LANGUAGE_SUBMIT": "Restartovat {APP_NAME}",
    "LANGUAGE_CANCEL": "Zrušit",
    "LANGUAGE_SYSTEM_DEFAULT": "Výchozí",
    "HEALTH_DATA_NOTIFICATION": "Nastavení Hlášení o zdraví",
    "HEALTH_FIRST_POPUP_TITLE": "Hlášení o zdraví {APP_NAME}",
    "HEALTH_DATA_DO_TRACK": "Sdílejte anonymní informace o používání {APP_NAME}",
    "HEALTH_DATA_NOTIFICATION_MESSAGE": "Kvůli vylepšování {APP_NAME} odesíláme společnosti Adobe pravidelně omezené &lt;strong&gt;anonymní&lt;/strong&gt; statistiky o používání {APP_NAME}. Tyto informace pomáhají upřednostnit některé funkce, předcházet chybám a všimnout si nedostatků v použitelnosti.&lt;br&gt;&lt;br&gt;Vaše data si můžete prohlédnout nebo zakázat jejich sdílení výběrem &lt;strong&gt;Nápověda &gt; Hlášení o zdraví&lt;/strong&gt;.&lt;br&gt;&lt;br&gt;&lt;a href=&#39;https://github.com/adobe/brackets/wiki/Health-Data&#39;&gt;Zjistěte více ke hlášení o zdraví {APP_NAME}&lt;/a&gt;",
    "HEALTH_DATA_PREVIEW": "Hlášení o zdraví {APP_NAME}",
    "HEALTH_DATA_PREVIEW_INTRO": "&lt;p&gt;Kvůli vylepšování {APP_NAME} odesíláme společnosti Adobe pravidelně omezené &lt;strong&gt;anonymní&lt;/strong&gt; statistiky o používání {APP_NAME}. Tyto informace pomáhají upřednostnit některé funkce, předcházet chybám a všimnout si nedostatků v použitelnosti. &lt;a href=&#39;https://github.com/adobe/brackets/wiki/Health-Data&#39;&gt;Zjistěte více ke hlášení o zdraví {APP_NAME}&lt;/a&gt; a jak je pro komunitu {APP_NAME} prospěšné, zatímco je chráněno vaše soukromí.&lt;/p&gt;&lt;p&gt;Níže je náhled dat, která budou odeslána v příštím hlášení o zdraví, &lt;em&gt;pokud&lt;/em&gt; je odesílání povoleno.&lt;/p&gt;",
    "INLINE_TIMING_EDITOR_TIME": "Doba",
    "INLINE_TIMING_EDITOR_PROGRESSION": "Postup",
    "BEZIER_EDITOR_INFO": "&lt;kbd&gt;↑&lt;/kbd&gt;&lt;kbd&gt;↓&lt;/kbd&gt;&lt;kbd&gt;←&lt;/kbd&gt;&lt;kbd&gt;→&lt;/kbd&gt; Posunout vybraný bod&lt;br&gt;&lt;kbd class=&#39;text&#39;&gt;Shift&lt;/kbd&gt; Posunout o deset jednotek&lt;br&gt;&lt;kbd class=&#39;text&#39;&gt;Tab&lt;/kbd&gt; Vyměnit body",
    "STEPS_EDITOR_INFO": "&lt;kbd&gt;↑&lt;/kbd&gt;&lt;kbd&gt;↓&lt;/kbd&gt; Zvýšení nebo snížení kroků&lt;br&gt;&lt;kbd&gt;←&lt;/kbd&gt;&lt;kbd&gt;→&lt;/kbd&gt; &#39;Start&#39; nebo &#39;End&#39;",
    "INLINE_TIMING_EDITOR_INVALID": "Stará hodnota &lt;code&gt;{0}&lt;/code&gt; není platná, proto zobrazená funkce byla změněna na &lt;code&gt;{1}&lt;/code&gt;. Dokument bude aktualizován při první úpravě.",
    "COLOR_EDITOR_CURRENT_COLOR_SWATCH_TIP": "Aktuální barva",
    "COLOR_EDITOR_ORIGINAL_COLOR_SWATCH_TIP": "Původní barva",
    "COLOR_EDITOR_RGBA_BUTTON_TIP": "RGBa formát",
    "COLOR_EDITOR_HEX_BUTTON_TIP": "Hex formát",
    "COLOR_EDITOR_HSLA_BUTTON_TIP": "HSLa formát",
    "COLOR_EDITOR_USED_COLOR_TIP_SINGULAR": "{0} (Použit {1}krát)",
    "COLOR_EDITOR_USED_COLOR_TIP_PLURAL": "{0} (Použit {1}krát)",
    "CMD_JUMPTO_DEFINITION": "Přejít na definici",
    "CMD_SHOW_PARAMETER_HINT": "Zobrazit nápovědu parametru",
    "NO_ARGUMENTS": "&lt;žádné parametry&gt;",
    "DETECTED_EXCLUSION_TITLE": "Inferenční problém JavaScriptového souboru",
    "DETECTED_EXCLUSION_INFO": "{APP_NAME} narazil na problémy při zpracování &lt;span class=&#39;dialog-filename&#39;&gt;{0}&lt;/span&gt;.&lt;br&gt;&lt;br&gt;Tento soubor nebude nadále používat nápovědy, funkci Přejít na definici a funkci Rychlá úprava. Pro opětovné zapnutí těchto funkcí, otevřete &lt;code&gt;.brackets.json&lt;/code&gt; ve vašem projektu a upravte &lt;code&gt;jscodehints.detectedExclusions&lt;/code&gt;.&lt;br&gt;&lt;br&gt;Pravděpodobně je to chyba {APP_NAME}. Pokud můžete poskytnout kopii tohoto souboru, prosíme &lt;a href=&#39;https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue&#39;&gt;nahlaste tuto chybu&lt;/a&gt; s odkazem na daný soubor.",
    "JSLINT_NAME": "JSLint",
    "CMD_ENABLE_QUICK_VIEW": "Rychlé zobrazení po přejetí kurzorem",
    "CMD_TOGGLE_RECENT_PROJECTS": "Nedávné projekty",
    "DOCS_MORE_LINK": "Zjistit více",
    "COLLAPSE_ALL": "Skrýt vše",
    "EXPAND_ALL": "Zobrazit vše",
    "COLLAPSE_CURRENT": "Skrýt aktuální",
    "EXPAND_CURRENT": "Zobrazit aktuální",
    "ERROR_RENAMING_DIRECTORY_TITLE": "Chyba při přejmenování složky",
    "ERROR_RENAMING_DIRECTORY": "Při pokusu o přejmenování složky &lt;span class=&#39;dialog-filename&#39;&gt;{0}&lt;/span&gt; došlo k chybě. {1}",
    "ERROR_DELETING_DIRECTORY_TITLE": "Chyba při odstraňování složky",
    "ERROR_DELETING_DIRECTORY": "Při pokusu o smazání adresáře &lt;span class=&#39;dialog-filename&#39;&gt;{0}&lt;/span&gt; došlo k chybě. {1}",
    "INVALID_DIRNAME_TITLE": "Neplatný název adresáře",
    "INVALID_DIRNAME_MESSAGE": "Název adresáře nesmí obsahovat žádná systémem rezervovaná slova, končit tečkami (.) nebo obsahovat některý z následujících znaků: &lt;code class=&#39;emphasized&#39;&gt;{1}&lt;/code&gt;",
    "ERROR_CREATING_DIRECTORY_TITLE": "Chyba při vytváření adresáře",
    "ERROR_CREATING_DIRECTORY": "Při pokusu o vytvoření adresáře &lt;span class=&#39;dialog-filename&#39;&gt;{1}&lt;/span&gt; došlo k chybě. {2}",
    "DND_MAX_FILE_SIZE_EXCEEDED": "soubor překračuje maximální podporovanou velikost: 3MB",
    "DND_UNSUPPORTED_FILE_TYPE": "nepodporovaný typ souboru",
    "DND_ERROR_UNZIP": "nelze rozbalit soubor",
    "DND_ERROR_UNTAR": "nelze rozbalit soubor",
    "DND_SUCCESS_UNZIP_TITLE": "Rozbalení úspěšně dokončeno",
    "DND_SUCCESS_UNTAR_TITLE": "Rozbalení úspěšně dokončeno",
    "DND_SUCCESS_UNZIP": "Úspěšně rozbalen &lt;b&gt;{0}&lt;/b&gt;.",
    "DND_SUCCESS_UNTAR": "Úspěšně rozbalen &lt;b&gt;{0}&lt;/b&gt;.",
    "UPLOAD_FILES_DIALOG_HEADER": "Nahrát soubory",
    "DRAG_AREA_UPLOAD_FILES_DIALOG_TEXT": "...nebo přetáhněte soubory zde.",
    "DROP_AREA_UPLOAD_FILES_DIALOG_TEXT": "OK, uvolněte soubory!",
    "UPLOADING_INDICATOR": "Nahrávání...",
    "BUTTON_FROM_YOUR_COMPUTER": "Z vašeho počítače...",
    "TAKE_A_SELFIE": "Vytvořit selfie...",
    "CMD_MOVE_FILE": "Přesunout do...",
    "PROJECT_ROOT": "Kořen projektu",
    "PICK_A_FOLDER_TO_MOVE_TO": "Vyberte složku",
    "ERROR_MOVING_FILE_DIALOG_HEADER": "Chyba při přesouvání",
    "UNEXPECTED_ERROR_MOVING_FILE": "Při pokusu o přesunutí {0} do {1} došlo k neočekávané chybě",
    "ERROR_MOVING_FILE_SAME_NAME": "Soubor nebo adresář s názvem {0} již existuje v {1}. Chcete-li pokračovat, jeden přejmenujte."
});
