/*
 * Copyright (c) 2012 Adobe Systems Incorporated. All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

/*jslint vars: true, plusplus: true, devel: true, nomen: true, indent: 4, maxerr: 50 */
/*global define */

define({

    "GENERIC_ERROR": "(erro {0})",
    "NOT_FOUND_ERR": "O arquivo /directory não foi encontrado.",
    "NOT_READABLE_ERR": "O arquivo /directory não pode ser lido.",
    "EXCEEDS_MAX_FILE_SIZE": "Arquivos maiores que {0} MB não pode ser aberto pelo {APP_NAME}.",
    "NO_MODIFICATION_ALLOWED_ERR": "O diretório de destino não pode ser modificado.",
    "NO_MODIFICATION_ALLOWED_ERR_FILE": "As permissões não permitem que você faça modificações.",
    "CONTENTS_MODIFIED_ERR": "O arquivo foi modificado fora do {APP_NAME}.",
    "UNSUPPORTED_ENCODING_ERR": "{APP_NAME} atualmente suporta apenas arquivos de texto codificados em UTF-8.",
    "FILE_EXISTS_ERR": "O arquivo ou diretório já existe.",
    "FILE": "arquivo",
    "FILE_TITLE": "Arquivo",
    "DIRECTORY": "diretório",
    "DIRECTORY_TITLE": "Diretório",
    "DIRECTORY_NAMES_LEDE": "Nome do diretório",
    "FILENAMES_LEDE": "Nomes dos arquivos",
    "FILENAME": "Nome do arquivo",
    "DIRECTORY_NAME": "Nome do diretório",
    "ERROR_LOADING_PROJECT": "Erro ao carregar o projeto",
    "OPEN_DIALOG_ERROR": "Ocorreu um erro enquanto abria a janela de arquivos. (erro {0})",
    "REQUEST_NATIVE_FILE_SYSTEM_ERROR": "Ocorreu um erro ao tentar carregar a pasta &lt;span class=&#39;dialog-filename&#39;&gt;{0}&lt;/span&gt;. (erro {1})",
    "READ_DIRECTORY_ENTRIES_ERROR": "Ocorreu um erro enquanto o conteudo do diretório era lido &lt;span class=&#39;dialog-filename&#39;&gt;{0}&lt;/span&gt;. (erro {1})",
    "ERROR_OPENING_FILE_TITLE": "Erro ao abrir o arquivo",
    "ERROR_OPENING_FILE": "Ocorreu um erro enquanto tentava abrir o arquivo &lt;span class=&#39;dialog-filename&#39;&gt;{0}&lt;/span&gt;. {1}",
    "ERROR_OPENING_FILES": "Ocorreu um erro enquanto tentava abrir os seguintes arquivos:",
    "ERROR_RELOADING_FILE_TITLE": "Erro ao recarregar as mudanças a partir do disco",
    "ERROR_RELOADING_FILE": "Ocorreu um erro ao tentar recarregar o arquivo &lt;span class=&#39;dialog-filename&#39;&gt;{0}&lt;/span&gt;. {1}",
    "ERROR_SAVING_FILE_TITLE": "Erro ao salvar o arquivo",
    "ERROR_SAVING_FILE": "Ocorreu um erro enquanto tentava salvar o arquivo &lt;span class=&#39;dialog-filename&#39;&gt;{0}&lt;/span&gt;. {1}",
    "ERROR_RENAMING_FILE_TITLE": "Erro ao renomear {0}",
    "ERROR_RENAMING_FILE": "Ocorreu um erro enquanto tentava renomear o {2} &lt;span class=&#39;dialog-filename&#39;&gt;{0}&lt;/span&gt;. {1}",
    "ERROR_DELETING_FILE_TITLE": "Erro ao excluir {0}",
    "ERROR_DELETING_FILE": "Ocorreu um erro enquanto tentava excluir o {2} &lt;span class=&#39;dialog-filename&#39;&gt;{0}&lt;/span&gt;. {1}",
    "INVALID_FILENAME_TITLE": "Inválido {0}",
    "INVALID_FILENAME_MESSAGE": "Os nomes de arquivo não pode usar quaisquer palavras reservadas pelo sistema, terminados com pontos (.) ou usar qualquer um dos seguintes caracteres: &lt;code class=&#39;emphasized&#39;&gt;{1}&lt;/code&gt;",
    "ENTRY_WITH_SAME_NAME_EXISTS": "Um arquivo ou pasta com o nome &lt;span class=&#39;dialog-filename&#39;&gt;{0}&lt;/span&gt; já existe.",
    "ERROR_CREATING_FILE_TITLE": "Erro ao Criar Arquivo",
    "ERROR_CREATING_FILE": "Ocorreu um erro ao tentar criar o arquivo &lt;span class=&#39;dialog-filename&#39;&gt;{1}&lt;/span&gt;. {2}",
    "ERROR_MIXED_DRAGDROP": "Não é possível abrir uma pasta e outros arquivos ao mesmo tempo.",
    "ERROR_KEYMAP_TITLE": "Erro ao ler mapa de teclas do usuário",
    "ERROR_KEYMAP_CORRUPT": "Seu arquivo de mapa de teclas não é um JSON válido. O arquivo será aberto para que você possa corrigir o formato.",
    "ERROR_LOADING_KEYMAP": "Seu arquivo de mapa de teclas não é um arquivo de texto com codificação UTF-8 válida e não pode ser carregado",
    "ERROR_RESTRICTED_COMMANDS": "Você não pode reatribuir atalhos para estes comandos: {0}",
    "ERROR_RESTRICTED_SHORTCUTS": "Você não pode reatribuir estes atalhos: {0}",
    "ERROR_MULTIPLE_SHORTCUTS": "Você está reatribuindo múltiplos atalhos para estes comandos: {0}",
    "ERROR_DUPLICATE_SHORTCUTS": "Você tem múltiplos vínculos para estes atalhos: {0}",
    "ERROR_INVALID_SHORTCUTS": "Estes atalhos são inválidos: {0}",
    "ERROR_NONEXISTENT_COMMANDS": "Você está atribuindo atalhos para comandos não existentes: {0}",
    "ERROR_PREFS_CORRUPT_TITLE": "Erro ao ler as preferências",
    "ERROR_PREFS_CORRUPT": "Seu arquivo de preferências não é um JSON válido. O arquivo será aberto para que você possa corrigir o formato. Você deverá reiniciar o {APP_NAME} para as alterações terem efeito.",
    "ERROR_IN_BROWSER_TITLE": "Opa! O {APP_NAME} não funciona em navegadores ainda.",
    "ERROR_IN_BROWSER": "O {APP_NAME} é criado em HTML, mas no momento ele é executado como um aplicativo de desktop para que você possa usá-lo para editar arquivos locais. Por favor, use o shell da aplicação do repositório &lt;b&gt;github.com/adobe/brackets-shell&lt;/b&gt; para executar {APP_NAME}.",
    "ERROR_MAX_FILES_TITLE": "Erro ao indexar arquivos",
    "ERROR_MAX_FILES": "Este projeto contém mais de 30.000 arquivos. Funcionalidades que operam em múltiplos arquivos podem ser desabilitadas ou se comportarem como se o projeto estivesse vazio. &lt;a href=&#39;https://github.com/adobe/brackets/wiki/Large-Projects&#39;&gt;Leia mais sobre como trabalhar com grandes projetos&lt;/a&gt;.",
    "ERROR_LAUNCHING_BROWSER_TITLE": "Erro ao abrir o navegador",
    "ERROR_CANT_FIND_CHROME": "O navegador Google Chrome não pôde ser encontrado. Por favor, verifique se ele está instalado.",
    "ERROR_LAUNCHING_BROWSER": "Ocorreu um erro ao iniciar o navegador. (erro {0})",
    "LIVE_DEVELOPMENT_ERROR_TITLE": "Erro no Live Preview",
    "LIVE_DEVELOPMENT_RELAUNCH_TITLE": "Conectando-se ao navegador",
    "LIVE_DEVELOPMENT_ERROR_MESSAGE": "Para que o Live Preview conecte-se, o Chrome deve ser reiniciado com a opção de depuração remota ativada.&lt;br /&gt;&lt;br /&gt;Gostaria de abrir o Chrome novamente e permitir a depuração remota?",
    "LIVE_DEV_LOADING_ERROR_MESSAGE": "Não foi possível carregar a página de Live Preview",
    "LIVE_DEV_NEED_HTML_MESSAGE": "Abra um arquivo HTML para iniciar Live Preview.",
    "LIVE_DEV_NEED_BASEURL_MESSAGE": "Para iniciar um live preview com um arquivo server-side, é preciso especificar uma URL Base para este projeto.",
    "LIVE_DEV_SERVER_NOT_READY_MESSAGE": "Erro ao iniciar o servidor HTTP para os arquivos do desenvolvimento em tempo real. Por favor, tente novamente.",
    "LIVE_DEVELOPMENT_INFO_TITLE": "Bem-vindo à Live Preview!",
    "LIVE_DEVELOPMENT_INFO_MESSAGE": "O Live Preview conecta o {APP_NAME} ao seu navegador. Ele abre uma prévia do seu arquivo HTML no navegador e atualiza a visualização em tempo real, enquanto você edita o código.&lt;br /&gt;&lt;br /&gt;Nesta versão inicial do {APP_NAME}, o Live Preview só funciona com o &lt;strong&gt;Google Chrome&lt;/strong&gt; e atualiza em tempo real enquanto você edita &lt;strong&gt;arquivos CSS&lt;/strong&gt;. Alterações em arquivos HTML ou JavaScript são automaticamente recarregados ao salvar.&lt;br /&gt;&lt;br /&gt;(Você só verá esta mensagem uma vez.)",
    "LIVE_DEVELOPMENT_TROUBLESHOOTING": "Para mais informações, veja &lt;a href=&#39;{0}&#39; title=&#39;{0}&#39;&gt;Solucionando erros de conexão com Live Development&lt;/a&gt;.",
    "LIVE_DEV_STATUS_TIP_NOT_CONNECTED": "Live Preview",
    "LIVE_DEV_STATUS_TIP_PROGRESS1": "Live Preview: Conectando…",
    "LIVE_DEV_STATUS_TIP_PROGRESS2": "Live Preview: Inicializando…",
    "LIVE_DEV_STATUS_TIP_CONNECTED": "Desconectar Live Preview",
    "LIVE_DEV_STATUS_TIP_OUT_OF_SYNC": "Live Preview (salve o arquivo para recarregar)",
    "LIVE_DEV_STATUS_TIP_SYNC_ERROR": "Live Preview (atualização interrompida devido a erro de sintaxe)",
    "LIVE_DEV_DETACHED_REPLACED_WITH_DEVTOOLS": "O Live Preview foi cancelado pois as ferramentas de desenvolvedor do navegador foram abertas",
    "LIVE_DEV_DETACHED_TARGET_CLOSED": "O Live Preview foi cancelado pois a página foi fechada no navegador",
    "LIVE_DEV_NAVIGATED_AWAY": "O Live Preview foi cancelado pois o navegador foi para uma página que não pertence a este projeto atual",
    "LIVE_DEV_CLOSED_UNKNOWN_REASON": "O Live Preview foi cancelado por uma razão desconhecida ({0})",
    "SAVE_CLOSE_TITLE": "Salvar alterações",
    "SAVE_CLOSE_MESSAGE": "Você quer salvar as alterações feitas no documento &lt;span class=&#39;dialog-filename&#39;&gt;{0}&lt;/span&gt;?",
    "SAVE_CLOSE_MULTI_MESSAGE": "Você quer salvar as alterações feitas aos seguintes arquivos?",
    "EXT_MODIFIED_TITLE": "Mudanças externas",
    "CONFIRM_FOLDER_DELETE_TITLE": "Confirmar exclusão",
    "CONFIRM_FOLDER_DELETE": "Você tem certeza que deseja remover a pasta &lt;span class=&#39;dialog-filename&#39;&gt;{0}&lt;/span&gt;?",
    "FILE_DELETED_TITLE": "Arquivo excluído",
    "EXT_MODIFIED_WARNING": "&lt;span class=&#39;dialog-filename&#39;&gt;{0}&lt;/span&gt;  foi modificado em {APP_NAME}.&lt;br /&gt;&lt;br /&gt;Você deseja salvar o arquivo e sobrescrevelo?",
    "EXT_MODIFIED_MESSAGE": "&lt;span class=&#39;dialog-filename&#39;&gt;{0}&lt;/span&gt; foi modificado de {APP_NAME}, mas possui alterações que não foram salvas em  {APP_NAME}.&lt;br /&gt;&lt;br /&gt;Qual versão você quer manter?",
    "EXT_DELETED_MESSAGE": "&lt;span class=&#39;dialog-filename&#39;&gt;{0}&lt;/span&gt; foi removido de {APP_NAME}, mas possui alterações não salvas em {APP_NAME}.&lt;br /&gt;&lt;br /&gt;Você quer manter as suas alterações?",
    "DONE": "Concluído",
    "OK": "OK",
    "CANCEL": "Cancelar",
    "DONT_SAVE": "Não salvar",
    "SAVE": "Salvar",
    "SAVE_AS": "Salvar como…",
    "SAVE_AND_OVERWRITE": "Sobrescrever",
    "DELETE": "Excluir",
    "BUTTON_YES": "Sim",
    "BUTTON_NO": "Não",
    "FIND_MATCH_INDEX": "{0} de {1}",
    "FIND_NO_RESULTS": "Nenhum resultado",
    "FIND_QUERY_PLACEHOLDER": "Localizar…",
    "REPLACE_PLACEHOLDER": "Substituir por…",
    "BUTTON_REPLACE_ALL": "Tudo…",
    "BUTTON_REPLACE_ALL_IN_FILES": "Substituir…",
    "BUTTON_REPLACE": "Substituir",
    "BUTTON_NEXT": "▶",
    "BUTTON_PREV": "◀",
    "BUTTON_NEXT_HINT": "Resultado seguinte",
    "BUTTON_PREV_HINT": "Resultado anterior",
    "BUTTON_CASESENSITIVE_HINT": "Diferenciar maiúsculas/minúsculas",
    "BUTTON_REGEXP_HINT": "Expressão regular",
    "REPLACE_WITHOUT_UNDO_WARNING_TITLE": "Substituir sem desfazer",
    "REPLACE_WITHOUT_UNDO_WARNING": "Porque mais de {0} arquivos precisam ser alterados, {APP_NAME} irá modificar arquivos não abertos no disco.&lt;br /&gt;Não será possível desfazer as modificações nestes arquivos.",
    "BUTTON_REPLACE_WITHOUT_UNDO": "Substituir sem desfazer",
    "OPEN_FILE": "Abrir arquivo",
    "SAVE_FILE_AS": "Salvar arquivo",
    "CHOOSE_FOLDER": "Escolha uma pasta",
    "RELEASE_NOTES": "Notas da versão",
    "NO_UPDATE_TITLE": "Você está atualizado!",
    "NO_UPDATE_MESSAGE": "Você está executando a versão mais recente do {APP_NAME}.",
    "FIND_REPLACE_TITLE_LABEL": "Substituir",
    "FIND_REPLACE_TITLE_WITH": "por",
    "FIND_TITLE_LABEL": "Encontrados",
    "FIND_TITLE_SUMMARY": "&amp;mdash; {0} {1} {2} em {3}",
    "FIND_NUM_FILES": "{0} {1}",
    "FIND_IN_FILES_SCOPED": "em &lt;span class=&#39;dialog-filename&#39;&gt;{0}&lt;/span&gt;",
    "FIND_IN_FILES_NO_SCOPE": "no projeto",
    "FIND_IN_FILES_ZERO_FILES": "Filtro exclui todos os arquivos {0}",
    "FIND_IN_FILES_FILE": "arquivo",
    "FIND_IN_FILES_FILES": "arquivos",
    "FIND_IN_FILES_MATCH": "resultado",
    "FIND_IN_FILES_MATCHES": "resultados",
    "FIND_IN_FILES_MORE_THAN": "Mais de ",
    "FIND_IN_FILES_PAGING": "{0}&amp;mdash;{1}",
    "FIND_IN_FILES_FILE_PATH": "&lt;span class=&#39;dialog-filename&#39;&gt;{0}&lt;/span&gt; {2} &lt;span class=&#39;dialog-path&#39;&gt;{1}&lt;/span&gt;",
    "FIND_IN_FILES_EXPAND_COLLAPSE": "Ctrl/Cmd + clique para expandir/comprimir tudo",
    "REPLACE_IN_FILES_ERRORS_TITLE": "Erro na substituição",
    "REPLACE_IN_FILES_ERRORS": "Os seguintes arquivos não foram modificados porque eles foram alterados antes da busca ou não puderam ser escritos.",
    "ERROR_FETCHING_UPDATE_INFO_TITLE": "Erro ao receber informações de atualização",
    "ERROR_FETCHING_UPDATE_INFO_MSG": "Houve um problema ao obter informações sobre a última atualização do servidor. Por favor, certifique-se de estar conectado à Internet e tente novamente.",
    "NEW_FILE_FILTER": "Adicionar filtro…",
    "CLEAR_FILE_FILTER": "Limpar filtro de arquivos",
    "NO_FILE_FILTER": "Nenhum filtro de arquivos",
    "EXCLUDE_FILE_FILTER": "Excetua {0}",
    "EDIT_FILE_FILTER": "Editar…",
    "FILE_FILTER_DIALOG": "Editar filtro",
    "FILE_FILTER_INSTRUCTIONS": "Exclui dos resultados os arquivos e pastas que correspondam a qualquer das strings, substrings ou &lt;a href=&#39;{0}&#39; title=&#39;{0}&#39;&gt;wildcards&lt;/a&gt; abaixo. Insira cada string em uma linha separada.",
    "FILTER_NAME_PLACEHOLDER": "Nome desta configuração de filtro (opcional)",
    "FILE_FILTER_CLIPPED_SUFFIX": "e outros {0}",
    "FILTER_COUNTING_FILES": "Contando arquivos…",
    "FILTER_FILE_COUNT": "Permite {0} de {1} arquivos {2}",
    "FILTER_FILE_COUNT_ALL": "Permite todos os {0} arquivos {1}",
    "ERROR_QUICK_EDIT_PROVIDER_NOT_FOUND": "Nenhuma edição rápida disponível para a posição do cursor",
    "ERROR_CSSQUICKEDIT_BETWEENCLASSES": "CSS Edição rápida: coloque o cursos em um nome de classe",
    "ERROR_CSSQUICKEDIT_CLASSNOTFOUND": "CSS Edição rápida: atributo class incompleto",
    "ERROR_CSSQUICKEDIT_IDNOTFOUND": "CSS Edição rápida: atributo id incompleto",
    "ERROR_CSSQUICKEDIT_UNSUPPORTEDATTR": "CSS Edição rápida: coloque o cursor em uma tag, class ou id",
    "ERROR_TIMINGQUICKEDIT_INVALIDSYNTAX": "CSS Edição rápida de função de temporização: sintaxe inválida",
    "ERROR_JSQUICKEDIT_FUNCTIONNOTFOUND": "Edição rápida JS: posicione o cursor sobre o nome da função",
    "ERROR_QUICK_DOCS_PROVIDER_NOT_FOUND": "Nenhum documento rápido disponível para a posição do cursor",
    "PROJECT_LOADING": "Carregando…",
    "UNTITLED": "Sem título",
    "WORKING_FILES": "Arquivos abertos",
    "TOP": "Início",
    "BOTTOM": "Fim",
    "LEFT": "Esquerda",
    "RIGHT": "Direita",
    "CMD_SPLITVIEW_NONE": "Sem divisão",
    "CMD_SPLITVIEW_VERTICAL": "Divisão vertical",
    "CMD_SPLITVIEW_HORIZONTAL": "Divisão horizontal",
    "SPLITVIEW_MENU_TOOLTIP": "Divida o editor verticalmente ou horizontalmente",
    "GEAR_MENU_TOOLTIP": "Configurar conjunto de trabalho",
    "SPLITVIEW_INFO_TITLE": "Já está aberto",
    "SPLITVIEW_MULTIPANE_WARNING": "O arquivo já está aberto em outro painel. {APP_NAME} em breve irá suportar a abertura de um mesmo arquivo em mais de um painel. Até lá, o arquivo será mostrado no painel onde já está aberto.&lt;br /&gt;&lt;br /&gt;(Você irá ver esta mensagem apenas uma vez.)",
    "KEYBOARD_CTRL": "Ctrl",
    "KEYBOARD_SHIFT": "Shift",
    "KEYBOARD_SPACE": "Espaço",
    "STATUSBAR_CURSOR_POSITION": "Linha {0}, Coluna {1}",
    "STATUSBAR_SELECTION_CH_SINGULAR": " — {0} coluna selecionada",
    "STATUSBAR_SELECTION_CH_PLURAL": " — {0} colunas selecionadas",
    "STATUSBAR_SELECTION_LINE_SINGULAR": " — {0} linha selecionada",
    "STATUSBAR_SELECTION_LINE_PLURAL": " — {0} linhas selecionadas",
    "STATUSBAR_SELECTION_MULTIPLE": " — {0} seleções",
    "STATUSBAR_INDENT_TOOLTIP_SPACES": "Clique para alterar a indentação para espaços",
    "STATUSBAR_INDENT_TOOLTIP_TABS": "Clique para alterar a indentação para tabulação",
    "STATUSBAR_INDENT_SIZE_TOOLTIP_SPACES": "Clique para alterar o número de espaços usados ao indentar",
    "STATUSBAR_INDENT_SIZE_TOOLTIP_TABS": "Clique para alterar a largura do caractere de tabulação",
    "STATUSBAR_SPACES": "Espaços:",
    "STATUSBAR_TAB_SIZE": "Tamanho da tabulação:",
    "STATUSBAR_LINE_COUNT_SINGULAR": "— {0} linha",
    "STATUSBAR_LINE_COUNT_PLURAL": "— {0} linhas",
    "STATUSBAR_USER_EXTENSIONS_DISABLED": "Extensões desativadas",
    "STATUSBAR_INSERT": "INS",
    "STATUSBAR_OVERWRITE": "OVR",
    "STATUSBAR_INSOVR_TOOLTIP": "Clique para alternar o cursor entre os modos Insert (INS) e Overwrite (OVR)",
    "STATUSBAR_LANG_TOOLTIP": "Clique para alterar o tipo de arquivo",
    "STATUSBAR_CODE_INSPECTION_TOOLTIP": "{0}. Clique para abrir/fechar o painel de relatórios.",
    "STATUSBAR_DEFAULT_LANG": "(padrão)",
    "STATUSBAR_SET_DEFAULT_LANG": "Definir como padrão para arquivos .{0}.",
    "ERRORS_PANEL_TITLE_MULTIPLE": "Problemas de {0}",
    "SINGLE_ERROR": "Um problema de {0}",
    "MULTIPLE_ERRORS": "{1} problemas de {0}",
    "NO_ERRORS": "Nenhum problema de {0} encontrado - bom trabalho!",
    "NO_ERRORS_MULTIPLE_PROVIDER": "Nenhum problema encontrado - bom trabalho!",
    "LINT_DISABLED": "A análise de código está desativada",
    "NO_LINT_AVAILABLE": "Nenhum analisador de código disponível para {0}",
    "NOTHING_TO_LINT": "Nada para analisar",
    "LINTER_TIMED_OUT": "{0} expirou após esperar durante {1} ms",
    "LINTER_FAILED": "{0} terminou com o erro: {1}",
    "FILE_MENU": "Arquivo",
    "CMD_FILE_NEW_UNTITLED": "Novo",
    "CMD_FILE_NEW": "Novo Arquivo",
    "CMD_FILE_NEW_FOLDER": "Nova pasta",
    "CMD_FILE_OPEN": "Abrir…",
    "CMD_ADD_TO_WORKING_SET": "Adicionar ao conjunto de trabalho",
    "CMD_OPEN_DROPPED_FILES": "Abrir arquivos largados",
    "CMD_OPEN_FOLDER": "Abrir pasta…",
    "CMD_FILE_CLOSE": "Fechar",
    "CMD_FILE_CLOSE_ALL": "Fechar todos",
    "CMD_FILE_CLOSE_LIST": "Fechar lista",
    "CMD_FILE_CLOSE_OTHERS": "Fechar outros",
    "CMD_FILE_CLOSE_ABOVE": "Fechar outros acima",
    "CMD_FILE_CLOSE_BELOW": "Fechar outros abaixo",
    "CMD_FILE_SAVE": "Salvar",
    "CMD_FILE_SAVE_ALL": "Salvar todos",
    "CMD_FILE_SAVE_AS": "Salvar como…",
    "CMD_LIVE_FILE_PREVIEW": "Live Preview",
    "CMD_TOGGLE_LIVE_PREVIEW_MB_MODE": "Habilitar Live Preview experimental",
    "CMD_RELOAD_LIVE_PREVIEW": "Forçar recarregamento do Live Preview",
    "CMD_PROJECT_SETTINGS": "Configurações do projeto…",
    "CMD_FILE_RENAME": "Renomear",
    "CMD_FILE_DELETE": "Excluir",
    "CMD_INSTALL_EXTENSION": "Instalar extensão…",
    "CMD_EXTENSION_MANAGER": "Gerenciador de extensões…",
    "CMD_FILE_REFRESH": "Atualizar árvore de arquivos",
    "CMD_QUIT": "Sair",
    "CMD_EXIT": "Sair",
    "EDIT_MENU": "Editar",
    "CMD_UNDO": "Desfazer",
    "CMD_REDO": "Refazer",
    "CMD_CUT": "Recortar",
    "CMD_COPY": "Copiar",
    "CMD_PASTE": "Colar",
    "CMD_SELECT_ALL": "Selecionar tudo",
    "CMD_SELECT_LINE": "Selecionar linha",
    "CMD_SPLIT_SEL_INTO_LINES": "Dividir seleção em linhas",
    "CMD_ADD_CUR_TO_NEXT_LINE": "Adicionar cursor à linha seguinte",
    "CMD_ADD_CUR_TO_PREV_LINE": "Adicionar cursor à linha anterior",
    "CMD_INDENT": "Indentar",
    "CMD_UNINDENT": "Diminuir indentação",
    "CMD_DUPLICATE": "Duplicar",
    "CMD_DELETE_LINES": "Excluir linha",
    "CMD_COMMENT": "Alternar comentário de linha",
    "CMD_BLOCK_COMMENT": "Alternar comentário de bloco",
    "CMD_LINE_UP": "Mover linha para cima",
    "CMD_LINE_DOWN": "Mover linha para baixo",
    "CMD_OPEN_LINE_ABOVE": "Abrir linha acima",
    "CMD_OPEN_LINE_BELOW": "Abrir linha abaixo",
    "CMD_TOGGLE_CLOSE_BRACKETS": "Fechar chaves automaticamente",
    "CMD_SHOW_CODE_HINTS": "Mostrar dicas de código",
    "FIND_MENU": "Localizar",
    "CMD_FIND": "Localizar",
    "CMD_FIND_NEXT": "Localizar próximo",
    "CMD_FIND_PREVIOUS": "Localizar anterior",
    "CMD_FIND_ALL_AND_SELECT": "Localizar tudo e selecionar",
    "CMD_ADD_NEXT_MATCH": "Adicionar próximo resultado à seleção",
    "CMD_SKIP_CURRENT_MATCH": "Pular e adicionar próximo resultado",
    "CMD_FIND_IN_FILES": "Localizar em arquivos",
    "CMD_FIND_IN_SELECTED": "Localizar no arquivo/diretório selecionado",
    "CMD_FIND_IN_SUBTREE": "Localizar em…",
    "CMD_REPLACE": "Substituir",
    "CMD_REPLACE_IN_FILES": "Substituir em arquivos",
    "CMD_REPLACE_IN_SELECTED": "Substituir no arquivo/diretório selecionado",
    "CMD_REPLACE_IN_SUBTREE": "Substituir em…",
    "VIEW_MENU": "Visualizar",
    "CMD_HIDE_SIDEBAR": "Esconder barra lateral",
    "CMD_SHOW_SIDEBAR": "Mostrar barra lateral",
    "CMD_INCREASE_FONT_SIZE": "Aumentar tamanho da fonte",
    "CMD_DECREASE_FONT_SIZE": "Diminuir tamanho da fonte",
    "CMD_RESTORE_FONT_SIZE": "Restaurar tamanho da fonte",
    "CMD_SCROLL_LINE_UP": "Rolar linha para cima",
    "CMD_SCROLL_LINE_DOWN": "Rolar linha para baixo",
    "CMD_TOGGLE_LINE_NUMBERS": "Números de linha",
    "CMD_TOGGLE_ACTIVE_LINE": "Destacar linha ativa",
    "CMD_TOGGLE_WORD_WRAP": "Quebra automática de linha",
    "CMD_LIVE_HIGHLIGHT": "Destacar Live Preview",
    "CMD_VIEW_TOGGLE_INSPECTION": "Analisar arquivos ao salvar",
    "CMD_SORT_WORKINGSET_BY_ADDED": "Ordenar por Data de Adição",
    "CMD_SORT_WORKINGSET_BY_NAME": "Ordenar por Nome",
    "CMD_SORT_WORKINGSET_BY_TYPE": "Ordenar por Tipo",
    "CMD_SORT_WORKINGSET_AUTO": "Ordenação automática",
    "CMD_THEMES": "Temas…",
    "NAVIGATE_MENU": "Navegar",
    "CMD_QUICK_OPEN": "Abertura rápida",
    "CMD_GOTO_LINE": "Ir para linha",
    "CMD_GOTO_DEFINITION": "Encontrar definição",
    "CMD_GOTO_FIRST_PROBLEM": "Ir ao primeiro erro/aviso",
    "CMD_TOGGLE_QUICK_EDIT": "Edição Rápida",
    "CMD_TOGGLE_QUICK_DOCS": "Documentos rápidos",
    "CMD_QUICK_EDIT_PREV_MATCH": "Resultado anterior",
    "CMD_QUICK_EDIT_NEXT_MATCH": "Resultado seguinte",
    "CMD_CSS_QUICK_EDIT_NEW_RULE": "Nova regra",
    "CMD_NEXT_DOC": "Documento seguinte",
    "CMD_PREV_DOC": "Documento anterior",
    "CMD_SHOW_IN_TREE": "Mostrar na árvore de arquivos",
    "CMD_SHOW_IN_EXPLORER": "Mostrar no Explorer",
    "CMD_SHOW_IN_FINDER": "Mostrar no Finder",
    "CMD_SHOW_IN_OS": "Mostrar no sistema operacional",
    "HELP_MENU": "Ajuda",
    "CMD_CHECK_FOR_UPDATE": "Verificar atualizações",
    "CMD_HOW_TO_USE_BRACKETS": "Como usar o {APP_NAME}",
    "CMD_SUPPORT": "Ajuda do {APP_NAME}",
    "CMD_SUGGEST": "Sugira um recurso",
    "CMD_RELEASE_NOTES": "Notas da versão",
    "CMD_GET_INVOLVED": "Envolva-se",
    "CMD_SHOW_EXTENSIONS_FOLDER": "Mostrar pasta de extensões",
    "CMD_HOMEPAGE": "Página do {APP_TITLE}",
    "CMD_TWITTER": "{TWITTER_NAME} no Twitter",
    "CMD_ABOUT": "Sobre o {APP_TITLE}",
    "CMD_OPEN_PREFERENCES": "Abrir arquivo de configurações",
    "CMD_OPEN_KEYMAP": "Abrir mapa de teclas do usuário",
    "EXPERIMENTAL_BUILD": "versão experimental",
    "DEVELOPMENT_BUILD": "versão de desenvolvimento",
    "RELOAD_FROM_DISK": "Recarregar do disco",
    "KEEP_CHANGES_IN_EDITOR": "Manter alterações no editor",
    "CLOSE_DONT_SAVE": "Fechar (não salvar)",
    "RELAUNCH_CHROME": "Abrir Chrome novamente",
    "ABOUT": "Sobre",
    "CLOSE": "Fechar",
    "ABOUT_TEXT_LINE1": "sprint {VERSION_MINOR} {BUILD_TYPE} {VERSION}",
    "ABOUT_TEXT_BUILD_TIMESTAMP": "timestamp da versão: ",
    "ABOUT_TEXT_LINE3": "Avisos, termos e condições de softwares de terceiros estão localizados em &lt;a href=&#39;{ADOBE_THIRD_PARTY}&#39;&gt;{ADOBE_THIRD_PARTY}&lt;/a&gt; e aqui incorporados por referência.",
    "ABOUT_TEXT_LINE4": "Documentação e código-fonte em &lt;a href=&#39;https://github.com/adobe/brackets/&#39;&gt;https://github.com/adobe/brackets/&lt;/a&gt;",
    "ABOUT_TEXT_LINE5": "Feito com ❤ e JavaScript por:",
    "ABOUT_TEXT_LINE6": "Várias pessoas (mas não estamos conseguindo carregar estes dados no momento).",
    "ABOUT_TEXT_WEB_PLATFORM_DOCS": "Web Platform Docs e logo gráfico Web Platform são licenciados sob a licença Creative Commons Attribution, &lt;a href=&#39;{WEB_PLATFORM_DOCS_LICENSE}&#39;&gt;CC-BY 3.0 Unported&lt;/a&gt;.",
    "UPDATE_NOTIFICATION_TOOLTIP": "Há uma nova versão do {APP_NAME} disponível! Clique aqui para mais detalhes.",
    "UPDATE_AVAILABLE_TITLE": "Atualização Disponível",
    "UPDATE_MESSAGE": "Ei, há uma nova versão do {APP_NAME} disponível. Aqui estão alguns dos novos recursos:",
    "GET_IT_NOW": "Obtenha agora!",
    "PROJECT_SETTINGS_TITLE": "Configurações do projeto para: {0}",
    "PROJECT_SETTING_BASE_URL": "URL base do Live Preview",
    "PROJECT_SETTING_BASE_URL_HINT": "Para usar um servidor local, insira uma URL como http://localhost:8000/",
    "BASEURL_ERROR_INVALID_PROTOCOL": "O protocolo {0} não é suportado pelo Live Preview&amp;mdash;por favor, use http: ou https: .",
    "BASEURL_ERROR_SEARCH_DISALLOWED": "A URL base não pode conter parâmetros de busca como &quot;{0}&quot;.",
    "BASEURL_ERROR_HASH_DISALLOWED": "A URL base não pode conter hashes como &quot;{0}&quot;.",
    "BASEURL_ERROR_INVALID_CHAR": "Caracteres especiais como &#39;{0}&#39; devem ser codificados para URL encoding.",
    "BASEURL_ERROR_UNKNOWN_ERROR": "Erro desconhecido ao parsear URL base",
    "EMPTY_VIEW_HEADER": "&lt;em&gt;Abra um arquivo enquanto este painel possui o foco&lt;/em&gt;",
    "CURRENT_THEME": "Tema atual",
    "USE_THEME_SCROLLBARS": "Usar barra de rolagens do tema",
    "FONT_SIZE": "Tamanho da fonte",
    "FONT_FAMILY": "Família da fonte",
    "THEMES_SETTINGS": "Configurações de temas",
    "BUTTON_NEW_RULE": "Nova Regra",
    "INSTALL": "Instalar",
    "UPDATE": "Atualizar",
    "REMOVE": "Remover",
    "OVERWRITE": "Sobrescrever",
    "CANT_REMOVE_DEV": "Extensões na pasta &quot;dev&quot; devem ser excluídas manualmente.",
    "CANT_UPDATE": "A atualização não é compatível com esta versão do {APP_NAME}.",
    "CANT_UPDATE_DEV": "Extensões na pasta &quot;dev&quot; não podem ser atualizadas automaticamente.",
    "INSTALL_EXTENSION_TITLE": "Instalar extensão",
    "UPDATE_EXTENSION_TITLE": "Atualizar extensão",
    "INSTALL_EXTENSION_LABEL": "URL da extensão",
    "INSTALL_EXTENSION_HINT": "URL do zip ou repositório GitHub da extensão",
    "INSTALLING_FROM": "Instalando extensão de {0}…",
    "INSTALL_SUCCEEDED": "Instalada com sucesso!",
    "INSTALL_FAILED": "Falha na instalação.",
    "CANCELING_INSTALL": "Cancelando…",
    "CANCELING_HUNG": "Cancelar a instalação está demorando muito. Um erro interno deve ter ocorrido.",
    "INSTALL_CANCELED": "Instalação cancelada.",
    "VIEW_COMPLETE_DESCRIPTION": "Ver descrição completa",
    "VIEW_TRUNCATED_DESCRIPTION": "Ver descrição reduzida",
    "INVALID_ZIP_FILE": "O conteúdo baixado não é um arquivo zip válido.",
    "INVALID_PACKAGE_JSON": "O arquivo package.json não é válido (o erro foi: {0}).",
    "MISSING_PACKAGE_NAME": "O arquivo package.json não especifica um nome de pacote.",
    "BAD_PACKAGE_NAME": "{0} é um nome de pacote inválido.",
    "MISSING_PACKAGE_VERSION": "O arquivo package.json não especifica uma versão de pacote.",
    "INVALID_VERSION_NUMBER": "O número da versão do pacote ({0}) é inválido.",
    "INVALID_BRACKETS_VERSION": "A string de compatibilidade com o {APP_NAME} ({0}) é inválida.",
    "DISALLOWED_WORDS": "As palavras ({1}) não são permitidas no campo {0}.",
    "API_NOT_COMPATIBLE": "A extensão não é compatível com esta versão do {APP_NAME}. Está instalada na sua pasta de extensões desativadas.",
    "MISSING_MAIN": "O pacote não tem um arquivo main.js.",
    "EXTENSION_ALREADY_INSTALLED": "Instalar este pacote irá substituir uma extensão instalada anteriormente. Sobrescrever a exensão antiga?",
    "EXTENSION_SAME_VERSION": "Este pacote está na mesma versão que o instalado atualmente. Sobrescrever a instalação existente?",
    "EXTENSION_OLDER_VERSION": "Este pacote está na versão {0}, que é mais antiga que a instalada atualmente ({1}). Sobrescrever a instalação existente?",
    "DOWNLOAD_ID_IN_USE": "Erro interno: ID de download já em uso.",
    "NO_SERVER_RESPONSE": "Não foi possível conectar-se ao servidor.",
    "BAD_HTTP_STATUS": "Aquivo não encontrado no servidor (HTTP {0}).",
    "CANNOT_WRITE_TEMP": "Não foi possível salvar o download em um arquivo temporário.",
    "ERROR_LOADING": "A extensão encontrou um erro ao inicializar.",
    "MALFORMED_URL": "A URL é inválida. Por favor, verifique se você a inseriu corretamente.",
    "UNSUPPORTED_PROTOCOL": "A URL precisa ser um endereço http ou https.",
    "UNKNOWN_ERROR": "Erro interno desconhecido.",
    "EXTENSION_MANAGER_TITLE": "Gerenciador de Extensões",
    "EXTENSION_MANAGER_ERROR_LOAD": "Não foi possível acessar o registro de extensões. Por favor,tente novamente mais tarde.",
    "INSTALL_EXTENSION_DRAG": "Arraste o .zip aqui ou",
    "INSTALL_EXTENSION_DROP": "Solte o .zip aqui ou",
    "INSTALL_EXTENSION_DROP_ERROR": "Instalação/atualização cancelada devido aos seguintes erros:",
    "INSTALL_FROM_URL": "Instalar a partir de URL…",
    "INSTALL_EXTENSION_VALIDATING": "Validando…",
    "EXTENSION_AUTHOR": "Autor",
    "EXTENSION_DATE": "Data",
    "EXTENSION_INCOMPATIBLE_NEWER": "Esta extensão requer uma versão mais recente do {APP_NAME}.",
    "EXTENSION_INCOMPATIBLE_OLDER": "Esta extensão atualmente só funciona com versões mais antigas do {APP_NAME}.",
    "EXTENSION_LATEST_INCOMPATIBLE_NEWER": "A versão {0} desta extensão exige uma versão mais recente do {APP_NAME}. Mas você pode instalar a versão {1} mais antiga.",
    "EXTENSION_LATEST_INCOMPATIBLE_OLDER": "A versão {0} desta extensão funciona apenas com versões mais antigas do {APP_NAME}. Mas você pode instalar a versão {1} mais recente.",
    "EXTENSION_NO_DESCRIPTION": "Sem descrição",
    "EXTENSION_MORE_INFO": "Mais informações...",
    "EXTENSION_ERROR": "Erro na extensão",
    "EXTENSION_KEYWORDS": "Palavras-chave",
    "EXTENSION_TRANSLATED_USER_LANG": "Traduzido para {0} idiomas, incluindo o seu",
    "EXTENSION_TRANSLATED_GENERAL": "Traduzido para {0} idiomas",
    "EXTENSION_TRANSLATED_LANGS": "Essa extensão foi traduzida para os seguintes idiomas: {0}",
    "EXTENSION_INSTALLED": "Instalada",
    "EXTENSION_UPDATE_INSTALLED": "Esta atualização foi baixada e será instalada quando você sair do {APP_NAME}.",
    "EXTENSION_SEARCH_PLACEHOLDER": "Pesquisar",
    "EXTENSION_MORE_INFO_LINK": "Mais",
    "BROWSE_EXTENSIONS": "Procurar extensões",
    "EXTENSION_MANAGER_REMOVE": "Remover extensão",
    "EXTENSION_MANAGER_REMOVE_ERROR": "Não foi possível remover uma ou mais extensões: {0}. O {APP_NAME} será encerrado mesmo assim.",
    "EXTENSION_MANAGER_UPDATE": "Atualizar extensão",
    "EXTENSION_MANAGER_UPDATE_ERROR": "Não foi possível atualizar uma ou mais extensões: {0}. O {APP_NAME} será encerrado mesmo assim.",
    "MARKED_FOR_REMOVAL": "Marcada para remoção",
    "UNDO_REMOVE": "Desfazer",
    "MARKED_FOR_UPDATE": "Marcada para atualização",
    "UNDO_UPDATE": "Desfazer",
    "CHANGE_AND_RELOAD_TITLE": "Alterar extensões",
    "CHANGE_AND_RELOAD_MESSAGE": "Para atualizar ou remover as extensões marcadas, o {APP_NAME} precisa ser recarregado. Você será solicitado a salvar suas alterações.",
    "REMOVE_AND_RELOAD": "Remover extensões e recarregar",
    "CHANGE_AND_RELOAD": "Alterar extensões e recarregar",
    "UPDATE_AND_RELOAD": "Atualizar extensões e recarregar",
    "PROCESSING_EXTENSIONS": "Processando alterações nas extensões…",
    "EXTENSION_NOT_INSTALLED": "Não foi possível remover a extensão {0} porque ela não estava instalada.",
    "NO_EXTENSIONS": "Nenhuma extensão instalada ainda.&lt;br&gt;Clique na aba Disponíveis acima para começar.",
    "NO_EXTENSION_MATCHES": "Nenhuma extensão corresponde à sua pesquisa.",
    "REGISTRY_SANITY_CHECK_WARNING": "NOTA: Estas extensões podem vir de diferentes autores e não do próprio {APP_NAME}. Extensões não são revisadas e tem prilégios locais totais. Tenha cuidado ao instalar extensões de fontes desconhecidas.",
    "EXTENSIONS_INSTALLED_TITLE": "Instaladas",
    "EXTENSIONS_AVAILABLE_TITLE": "Disponíveis",
    "EXTENSIONS_THEMES_TITLE": "Temas",
    "EXTENSIONS_UPDATES_TITLE": "Atualizações",
    "INLINE_EDITOR_NO_MATCHES": "Nenhum resultado.",
    "INLINE_EDITOR_HIDDEN_MATCHES": "Todas as correspondências foram ocultadas. Expanda os arquivos listados na direita para ver os resultados.",
    "CSS_QUICK_EDIT_NO_MATCHES": "Nenhuma regra CSS corresponde à sua seleção.&lt;br&gt; Clique em &quot;Nova regra&quot; para criar uma.",
    "CSS_QUICK_EDIT_NO_STYLESHEETS": "Seu projeto não tem uma folha de estilos.&lt;br&gt;Crie uma para adicionar regras CSS.",
    "IMAGE_VIEWER_LARGEST_ICON": "maior",
    "UNIT_PIXELS": "pixels",
    "DEBUG_MENU": "Depurar",
    "ERRORS": "Erros",
    "CMD_SHOW_DEV_TOOLS": "Mostrar ferramentas do desenvolvedor",
    "CMD_REFRESH_WINDOW": "Recarregar com extensões",
    "CMD_RELOAD_WITHOUT_USER_EXTS": "Recarregar sem extensões",
    "CMD_NEW_BRACKETS_WINDOW": "Nova janela do {APP_NAME}",
    "CMD_SWITCH_LANGUAGE": "Alterar idioma…",
    "CMD_RUN_UNIT_TESTS": "Executar testes",
    "CMD_SHOW_PERF_DATA": "Mostrar dados de desempenho",
    "CMD_ENABLE_NODE_DEBUGGER": "Habilitar depurador do Node",
    "CMD_LOG_NODE_STATE": "Registrar estado do Node no console",
    "CMD_RESTART_NODE": "Reiniciar Node",
    "CMD_SHOW_ERRORS_IN_STATUS_BAR": "Mostrar erros na barra de status",
    "CMD_OPEN_BRACKETS_SOURCE": "Abrir local do Brackets",
    "LANGUAGE_TITLE": "Alterar idioma",
    "LANGUAGE_MESSAGE": "Idioma:",
    "LANGUAGE_SUBMIT": "Reiniciar {APP_NAME}",
    "LANGUAGE_CANCEL": "Cancelar",
    "LANGUAGE_SYSTEM_DEFAULT": "Padrão do sistema",
    "INLINE_TIMING_EDITOR_TIME": "Tempo",
    "INLINE_TIMING_EDITOR_PROGRESSION": "Progresso",
    "BEZIER_EDITOR_INFO": "&lt;kbd&gt;↑&lt;/kbd&gt;&lt;kbd&gt;↓&lt;/kbd&gt;&lt;kbd&gt;←&lt;/kbd&gt;&lt;kbd&gt;→&lt;/kbd&gt; Move o ponto selecionado&lt;br&gt;&lt;kbd class=&#39;text&#39;&gt;Shift&lt;/kbd&gt; Move dez unidades&lt;br&gt;&lt;kbd class=&#39;text&#39;&gt;Tab&lt;/kbd&gt; Troca pontos",
    "STEPS_EDITOR_INFO": "&lt;kbd&gt;↑&lt;/kbd&gt;&lt;kbd&gt;↓&lt;/kbd&gt; Aumenta ou diminui passos&lt;br&gt;&lt;kbd&gt;←&lt;/kbd&gt;&lt;kbd&gt;→&lt;/kbd&gt; &#39;Start&#39; ou &#39;End&#39;",
    "INLINE_TIMING_EDITOR_INVALID": "O valor antigo &lt;code&gt;{0}&lt;/code&gt; não é válido, então a função exibida foi alterada para &lt;code&gt;{1}&lt;/code&gt;. O documento será atualizado com a primeira edição.",
    "COLOR_EDITOR_CURRENT_COLOR_SWATCH_TIP": "Cor atual",
    "COLOR_EDITOR_ORIGINAL_COLOR_SWATCH_TIP": "Cor original",
    "COLOR_EDITOR_RGBA_BUTTON_TIP": "RGBa formato",
    "COLOR_EDITOR_HEX_BUTTON_TIP": "Formato hexadecimal",
    "COLOR_EDITOR_HSLA_BUTTON_TIP": "Formato HSLa",
    "COLOR_EDITOR_USED_COLOR_TIP_SINGULAR": "{0} (Usado {1} vez)",
    "COLOR_EDITOR_USED_COLOR_TIP_PLURAL": "{0} (Uzado {1} vezes)",
    "CMD_JUMPTO_DEFINITION": "Ir para a definição",
    "CMD_SHOW_PARAMETER_HINT": "Mostrar sugestão de parâmetro",
    "NO_ARGUMENTS": "&lt;sem parametrôs&gt;",
    "DETECTED_EXCLUSION_TITLE": "JavaScript Arquivo com problema de inferência",
    "DETECTED_EXCLUSION_INFO": "Brackets enfrentou um problema ao processar: &lt;span class=&#39;dialog-filename&#39;&gt;{0}&lt;/span&gt;.&lt;br&gt;&lt;br&gt;Este arquivo não será mais processado para dicas de código, definições ou edição rápida. Para reverter, abra &lt;code&gt;.brackets.json&lt;/code&gt; em seu projeto e edite &lt;code&gt;jscodehints.detectedExclusions&lt;/code&gt;.&lt;br&gt;&lt;br&gt;Este provavelmente é um bug do Brackets. Se você pode fornecer uma cópia deste arquivo, por favor &lt;a href=&#39;https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue&#39;&gt;registre um bug&lt;/a&gt; com um link para o arquivo mencionado aqui.",
    "JSLINT_NAME": "JSLint",
    "CMD_ENABLE_QUICK_VIEW": "Nota rápida no Hover",
    "CMD_TOGGLE_RECENT_PROJECTS": "Projetos Recentes",
    "DOCS_MORE_LINK": "Saiba mais",
    "COLLAPSE_ALL": "Dobrar Tudo",
    "EXPAND_ALL": "Expandir Tudo",
    "COLLAPSE_CURRENT": "Dobrar Posição Atual",
    "EXPAND_CURRENT": "Expandir Posição Atual",
    "ERROR_RENAMING_DIRECTORY_TITLE": "Erro ao Renomear o Diretório",
    "ERROR_RENAMING_DIRECTORY": "Ocorreu um erro ao tentar renomear o diretório &lt;span class=&#39;dialog-filename&#39;&gt;{0}&lt;/span&gt;. {1}",
    "ERROR_DELETING_DIRECTORY_TITLE": "Erro ao Excluir o Diretório",
    "ERROR_DELETING_DIRECTORY": "Ocorreu um erro ao tentar excluir o diretório &lt;span class=&#39;dialog-filename&#39;&gt;{0}&lt;/span&gt;. {1}",
    "INVALID_DIRNAME_TITLE": "Nome de Diretório Inválido",
    "INVALID_DIRNAME_MESSAGE": "Os nomes de pastas não podem usar quaisquer palavras reservadas pelo sistema, terminados com pontos (.) ou usar qualquer um dos seguintes caracteres: &lt;code class=&#39;emphasized&#39;&gt;{1}&lt;/code&gt;",
    "ERROR_CREATING_DIRECTORY_TITLE": "Erro ao Criar Diretório",
    "ERROR_CREATING_DIRECTORY": "Ocorreu um erro ao tentar criar o diretório &lt;span class=&#39;dialog-filename&#39;&gt;{1}&lt;/span&gt;. {2}",
    "DND_MAX_FILE_SIZE_EXCEEDED": "arquivo excede o tamanho máximo suportado: 3MB",
    "DND_UNSUPPORTED_FILE_TYPE": "tipo de arquivo não suportado",
    "DND_ERROR_UNZIP": "não foi possível descompactar o arquivo",
    "DND_ERROR_UNTAR": "não foi possível descompactar o arquivo",
    "DND_SUCCESS_UNZIP_TITLE": "Arquivo zipado com sucesso",
    "DND_SUCCESS_UNTAR_TITLE": "Arquivo zipado com sucesso",
    "DND_SUCCESS_UNZIP": "Arquivos zipados &lt;b&gt;{0}&lt;/b&gt;.",
    "DND_SUCCESS_UNTAR": "Arquivos zipados &lt;b&gt;{0}&lt;/b&gt;.",
    "UPLOAD_FILES_DIALOG_HEADER": "Carregar arquivos",
    "DRAG_AREA_UPLOAD_FILES_DIALOG_TEXT": "...ou solte os arquivos aqui.",
    "DROP_AREA_UPLOAD_FILES_DIALOG_TEXT": "OK, solte os arquivos!",
    "UPLOADING_INDICATOR": "Enviando...",
    "BUTTON_FROM_YOUR_COMPUTER": "Do seu computador...",
    "TAKE_A_SELFIE": "Tire uma selfie...",
    "CMD_MOVE_FILE": "Mover para...",
    "PROJECT_ROOT": "Página do projeto",
    "PICK_A_FOLDER_TO_MOVE_TO": "Escolha uma pasta",
    "ERROR_MOVING_FILE_DIALOG_HEADER": "Erro ao mover",
    "UNEXPECTED_ERROR_MOVING_FILE": "Ocorreu um erro enquanto tentavamos mover {0} para {1}",
    "ERROR_MOVING_FILE_SAME_NAME": "Um arqiovo ou pasta com o nome {0} já existe em {1}. Considere renomear qualquer um deles para continuar."
});
